application: addictingwordgames
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "300d 5h"

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /static
  static_dir: static
  http_headers:
    Vary: Accept-Encoding
- url: /channel.html
  static_files: channel.html
  upload: channel.html
  expiration: "300d"
# - url: /(.*)html
  # static_files: \1html
  # upload: \1html
- url: /BingSiteAuth.xml
  static_files: BingSiteAuth.xml
  upload: BingSiteAuth.xml
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /mochi.html
  static_files: mochi.html
  upload: mochi.html
- url: /achievement-hard.html
  static_files: achievement-hard.html
  upload: achievement-hard.html
  expiration: "0d 1h"
- url: /achievement-medium.html
  static_files: achievement-medium.html
  upload: achievement-medium.html
  expiration: "0d 1h"
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
builtins:
- deferred: on

pagespeed:
  url_blacklist:
  - http://www.addictingwordgames.com/sitemap
  # - http://www.wordsmashing.com/manifest.webapp
  # - https://wordsmashing.appspot.com/buy
  enabled_rewriters:
  - CollapseWhitespace
  - CombineHeads
  # - ElideAttributes
  - RemoveComments
  - MinifyCss
#  - InlineJs
  # - LeftTrimUrls

inbound_services:
- warmup

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^node_modules.*$
