descriptions = [
    "explore 4 letter words",
    "",
    "STEAL EVERYTHING",
    "do you have any regrets?",
    "Be a goose. Be smart.",
    "A simulation game that is heavier than it looks.",
    "A Wordle clone for the Nintendo Game Boy (&amp; Color) / Color and Analogue Pocket / MegaDuck",
    "Normal isn't what it used to be.",
    "Guess about your favorite food or Pokemons!",
    "The hangman platformer",
    "A crossword puzzle about game development",
    "Wordle, but each game goes on forever...",
    "A word game roguelike",
    "Find the right words!",
    "A stylish arcade-like word game for DOS (and more)",
    "Brain bending word puzzler!",
    "Beautifully simple. Endlessly challenging.",
    "Word puzzles with Sunday morning vibes",
    "Crawl through this dungeon, using your word skills to defeat the monsters!",
    "Striple is a daily word puzzle with a stripping lady",
    "A cute fox girl explores her small hometown on her way to a date with a friend.",
    "Word scramble meets adventure gaming, Halloween Edition",
    "Play a game of Wordly with a tower defence twist once a day!",
    "challenging word puzzler",
    "The kinky side of a classic game",
    "5-In-1",
    "Slip into the role of an unusual HERO and find the last letter to restore hope in a merciless world.",
    "In a world populated by words, the typo bounty hunter must track down deviant misspellings, and deliver their sentence.",
    "The hit daily word guessing game, now for your Playdate!",
    "Multiplayer word game",
    "Mysterious word game for Playdate with 400+ levels and unlockable items &amp; achievements!",
    "A little word game.",
    "Nordic Game Jam 2018 Entry",
    "Practise your typing while playing !",
    "A simple infinite version of Wordle",
    "",
    "A snake-inspired roguelike about words",
    "Sliding tiles puzzle game [Amiga]",
    "",
    "Multiplayer drawing and word guessing game",
    "It's your job to take care of him.",
    "Use icons &amp; guess words!",
    "Words for Evil is a fast paced word game combined with a fantasy RPG.",
    "A surrealist interactive word game",
    "Wordle as a roguelike. Made for 7DRL 2022",
    "Once upon a time, there lived a Princess and her Knight.",
    "A letter-placing platformer!",
    "Match colorful tiles &amp; solve brain-teasing anagrams across 4 unique game modes in this relaxing puzzler",
    "Player is not cat. Player is level. Player push the cat. (GMTK Game Jam 2023)",
    "Stay a while. Stay forever. Won't you come outside?",
    "This is a calm game made to help autistic children to work on perception and logic",
    "",
    "Sticks and stones may break my bones, but words are ghosts that haunt me. A short word game! (ChainLetter Jam)",
    "Write poems, get paid, try to avoid comitting high treason.",
    "a gothic action word game",
    "A relaxing lofi word game",
    "Turdle - A shit take on Wordle",
    "a word puzzle game with an angry armadillo",
    "a word puzzle game with an angry armadillo",
    "A unique daily word game that expands your vocabulary!",
    "A interactive story",
    "Are you still trying hard to memorize Japanese words?Let's learn it in easy.",
    "you better not guess too quick or else he'll get ya",
    "You play as a Mayor of a little village who wants to gather votes in anticipation of the upcoming elections.",
    "When you fall into another world, you set out to find a way home. Along the way, you touch the lives of many.",
    "The illegitimate child of Slay the Spire &amp; Bookworm",
    "A multiplayer word game where the objective is NOT to complete the word",
    "When communication isn't part of your mercenary training...",
    "A skiing game for people who like words and chocolates",
    "An NES clone of the world-famous Wordle with keyboard support!",
    "A puzzle adventure game based on anagrams",
    "Serpent-like word search",
    "The word game.",
    "He is no mere Hangman.  Made for Hangman Jam in 2020.",
    "MMORPG geolocation game, сapture of territories, clan battles",
    "​A word association game that is based on song titles. Are you hip enough to play?",
    "Spell words to capture territory and defeat your opponent",
    "A word game in an arcade machine",
    "Wordle, but Pig Latin",
    "The popular 5-letter word guessing game now for Windows 3.1.",
    "That word game, but smaller.",
    "An Arcade Word Puzzle",
    "Social Chat With AI Characters",
    "Cobble together a dating profile with the best words you can snag!",
    "Quick and Simple Word Puzzle Game",
    "Create words by placing blocks on the board",
    "You forgot to study.",
    "I redid the mechanics of the game Baba Is You, (in less beautiful)",
    "",
    "Hakbank'ta oluşan sorunları çözebilecek misin?",
    "Logical puzzles for everyone. Are you ready to discover how smart you are?",
    "Buy / Recombine / Sell words for a profit",
    "an orthographic archipelago enigma",
    "A word switch cooking game where the results are up to you.",
    "A Game of Vigilant Typesetting",
    "Port of the viral game Wordle for the Fairchild Channel F",
    "Alone or together?",
    "A short game about books and other stuff.",
    "Competitive Hangman Party Game",
    "Master your word spelling skill in the secret word-challenge!",
    "It's like that other word game but it's way longer and it doesn't cost anything.",
    "Use the words \"To, Too, and Two\" to find success in this comedic puzzle game!",
    "Daily word scrambling puzzle",
    "Start with \"nothing\" and grasp \"victory\" by moving letters around.",
    "Updated Demo after feedback, still lots of monkeys.",
    "Racing Scrabble",
    "A rhythm based typing game",
    "Addictive word based puzzles especially for the genius! Infinite fun!",
    "A short game for Ludum Dare 49 about words",
    "A simple word game about finding the longest word by eliminating letters.",
    "Play online with up to 12 people per game. Guess your opponents hidden words while hiding your own from them",
    "A new classic word puzzle!",
    "Guess the secret word based on the position of the letters",
    "",
    "Find your voice in this five-minute romantic puzzle.",
    "puzzle word lockdown pandemic story",
    "Grow the word more than the computer can",
    "Spin some cubes, find the words! An entry for the first mizjam.",
    "A Wordle clone for Playdate",
    "",
    "Tiny city-builder",
    "Compete to find the longest word! (Multiplayer)",
    "A soup-tastic word puzzle adventure set in a fantasy supermarket !",
    "Yet Another Wheel of Fortune For Amiga",
    "Help Santa’s cats to organise Christmas!",
    "Reventure pero cutre",
    "Make links between words",
    "The space spelling game nobody asked for",
    "Hack Computers and Crack Passwords",
    "You are the game the computer plays",
    "Semantic Construct is a puzzle game about building a world with words.",
    "Be like Charman!",
    "",
    "Sell illegal spells on the internet to get by in this arcade word puzzler!",
    "Ever feel like running from a deadly fog while testing your spelling skills?",
    "A VR Linguistic Adventure Through a Dying Psyche",
    "A new casual word game puzzle",
    "He gets really mad when someone misspells his name",
    "Mr Honk awaits you in his quite thick demeanour in speedy word game!",
    "Spy VS Spy game in the Cold War",
    "You serve alien customers aboard the Hubble Convenience Store. You translate their requests for \"Earth Specials.\"",
    "Find the proper words in this challenging and customizable puzzle game.",
    "A combination word and idle game - built for Mini Jam 71",
    "Gamejam Game for the ManaSoup Jam 2021",
    "Play as a youngster with a cursed name as she takes revenge on rhyming words in this short puzzle game.",
    "Use words to defeat your enemies / the world!",
    "A short word game where you can test your vocabulary skills!",
    "Click chains of tiles to make words",
    "Thai word matching game",
    "Game made for the \"Quarantine Jam\"",
    "Collect items, make words!",
    "Discover locations in this exciting word scramble game.",
    "To the one who sets foot in this shrine...",
    "A word finding game",
    "guess a maximum words  from a given  list of letters",
    "A JPRG mixed with Word Game.",
    "A silly word game featuring 90s hip hop tropes",
    "Solve the words puzzles and help the nine ghosts progress through easy and hard levels!",
    "Buy vowels to create words in this very normal game.",
    "A simple Hangman style game created with the Godot Game Engine.",
    "An open source wordle clone",
    "Hard Conversation Explorer",
    "An addictive word based puzzle game with infinite replay value",
    "",
    "A Love Story",
    "A puzzle/story about reading between the lines",
    "Arrange letters in a grid to spell words and build combos. It's Panel de Pon made letter perfect!",
    "A wall message collage simulator!",
    "6 letters. 5 guesses. 1 streak.",
    "Play trivias of local restaurants",
    "Word Puzzle Game Template",
    "A wordy board game",
    "Find a word to delay the landing",
    "Do you want to be a game writer? Then let's go on a very nonsense adventure!",
    "Word game where you make new words that are one letter different from the original word.",
    "A Wordle variant created entirely using Twine.",
    "Made for Ludum Dare 51",
    "",
    "Speak the word the townsfolk are trying to remember!",
    "文字冒险游戏，2022腾讯游戏策划公开课银奖",
    "Roguelike with Wordsearch puzzles",
    "What will you find beyond the dunes?",
    "A puzzle game about transforming words",
    "Can you unscramble the words before the time ticks down?",
    "Match 3 meets scrabble!",
    "A spelling-based witchcraft game",
    "A cross-word anagrams puzzle game for MS-DOS targeting 8088 / CGA / 384KB",
    "An exciting mix between a word and a trivia game. Put syllables back together as fast as possible.",
    "Contract Dyslexia",
    "A honey-filled action word game",
    "A mix of mastermind and hangman!",
    "make words with blocks before time runs out",
    "Para quem já tem a cabeça quebrada",
    "Short horror FMV word guessing game",
    "A program designed for children to help them learn the look and sound of letters and their placement on the keyboard.",
    "A word game that is made for educational purposes.",
    "A non-profit, educational word game narrated by Richard Dawkins",
    "word game in Hungarian and in English",
    "Use the brand names of the applications/software to get the letters of the shown word!",
    "A nexus of nomenclature",
    "A simple daily word game where you must find words by moving tiles into the correct position on a grid.",
    "Compose a haiku from random words in twenty seconds.",
    "Letter-guessing meets space-ship piloting!",
    "Use the power of Language and Imagination to get past reality-bending puzzles!",
    "Sanojen arvailua",
    "A rogue-like word-puzzle RPG.",
    "A small game to practice for your next Wordle of the day!",
    "A puzzle game where a kitten is searching for someone to adopt him.",
    "Anagram brain teaser",
    "El juego de las palabras raras",
    "The classic game show, but with the DOS prompt instead of Vanna.",
    "Wordle meets Bookworm Adventures. Spell your way to victory in this epic showdown.",
    "Hand Eye Society SuperJAM 2022",
    "A card-based word game with area-control mechanics.",
    "Remove it to make another word",
    "Type with your friends and test your typing speed.",
    "A poetic game of words in motion",
    "Who said that mathematics wouldn't be useful for stealing?",
    "How many words can you create from 6 letters?",
    "Word search with unique letters",
    "Fun and simple 3D Hangman game",
    "Relaxing anagram and word jumble game in a farm setting.",
    "Use the locked letter before time runs out!",
    "A word game where you fight your way through waves of enemies.",
    "A fun word guessing game",
    "Guess the name of a TV show.",
    "We approve our better bouncing about.",
    "Do you remember this game?",
    "Your daily word puzzle (of flesh)! 🧩",
    "Build chains with words falling in a cascading pattern.",
    "The ultimate word connecting game with over 10,000 exciting levels.",
    "My first simple  game project",
    "",
    "Spin the wheel!",
    "A chill word guessing game with daily goals and a fun mini-game.",
    "Uma mistura de Jogo da Memória com Palavras-Cruzadas",
    "",
    "A fast-paced word game that will put your vocabulary to the test",
    "Ludum Dare 51 puzzle game",
    "Discover 140+ words spread in 4 sunny themes! Handcrafted grids, hints, mini-objectives &amp; more!!!",
    "Swipe words to level up your buildings!",
    "word/tile game",
    "How fast can you read backwards?",
    "Guess the password from the given clue.",
    "Save your cat by killing demons with typing",
    "Falling shape word game!",
    "Guess the secret word from adjacent letter clues",
    "",
    "The viral word guessing game, now in your pocket!",
    "A free Wordle-based platform adventure",
    "Aconsegueix desxifrar el text secret",
    "​Learn typing with Fast Typing Master and find how fast you can type.",
    "A pixel game about individual choices and system mechanism.",
    "Wordle but with colors instead of words",
    "A Math Game for the ages!",
    "A 3D word game. Find hidden words!",
    "Write a word based on last 3 letters of last word.",
    "the word game where *nobody* waits their turn",
    "A simple daily word puzzle where you must find all the names of items on various themes.",
    "Guess the word game, organised into themes, based on the traditional game of hangman with added Tiki flavour!",
    "The Brazilian Portuguese version of Wordle.",
    "Word game + Solitaire. You need to clear the board by doing 5 letter words.",
    "",
    "over 1000 words",
    "Made for the GMTK game jam 2019",
    "Make 160 words to win the game",
    "",
    "March's game. Guess the daily phrase!  *Works best on mobile.",
    "Play the immensely popular game Wordle now against your friends!",
    "A simple delve into space to find the letters you need to EXPLORE",
    "Wordle clone for MS-DOS",
    "Five chances to guess a word",
    "The Totally Terrific Touch-Typing Trainer",
    "The original daily term guessing game!",
    "Pictionary with descriptions",
    "",
    "Word Game Meets Fantasy Turn-Based RPG",
    "",
    "RPG educativo para ensino da língua inglesa. Protótipo de Demonstração v0.02",
    "Cast Spells by unscrambling words",
    "Make your way from a word to another by going through suggested terms.",
    "Word Puzzle game",
    "Japanese learning RPG",
    "Simple word game. Guess as many as possible, use all the letters to advance.",
    "A Crossy Adventure through words and puzzles.",
    "A game about making words from nothing.",
    "A wordle-type game with a twist; after each guess, you're told if each letter is higher or lower in the secret word.",
    "Fun Wordplay Party Game",
    "Use your vocabulary and creativity to spell spells!",
    "Joke port of wordle for MS-DOS (tested on 6.22)",
    "A prototype of the game Wordle, follow our guide to make one yourself!",
    "An extra mode prototype for NES Wordle!",
    "Wordmoji is an all things popular culture guessing and trivia game",
    "A fast-paced word building game",
    "Puzzle game built around joining letters together to solve puzzles",
    "",
    "Be Creative",
    "Its Hangman, but with your Friends!",
    "Sit down and enjoy Sudoku, Word searches, and Crossword puzzles",
    "Hacking isn't about mashing your keyboard as fast as you can, not when you're the second best.",
    "A Fast-paced word search through the digital rain.",
    "A puzzle game where you make the right words by combining dice!",
    "Learn and practice touch-typing in a fun, retro-environment",
    "No time to explain, need to save the princess!",
    "Daily Word Puzzle for PlayDate",
    "fallout4 terminal hack minigame",
    "Keep \"IT\" alive - Get it... Like computers... hah.",
    "Juego de palabras que incluye lagartijas y efectos sonoros. /Wordgame that includes lizards and sound effects.",
    "A magnetic text adventure about fast-talking and myth-making in Ancient Greece",
    "a gameboy (color) word (and block) game!",
    "Word Addiction Breaks All the Rules!",
    "Word Search - Relax with our classic word search puzzles game!",
    "",
    "Worm your way around the page to solve the puzzles!",
    "¿Podrás de derribar los edificios demasiado altos  antes de que acabe el tiempo?",
    "Fun word finder game like Boggle with added twists!",
    "The Imaginative Word Doodling Game",
    "",
    "Wordle clone in toki pona language",
    "Play Wordle with 4, 5, 6, or 7-letter words, as many times a day as you like.",
    "The sequel of ToyCarSim, contains some of the best minigame from Game-A-Week 2020!",
    "",
    "Dark horror FMV word scramble game",
    "A Madlib-Em-Up word game where you play as a train that forgot to write their wedding vows.",
    "Walk-Simulation-and-RPG-like Documentary Game on term Discrimination, Clichee, Stereotype etc",
    "My entry for Weekly Game Jam (Week 81).",
    "",
    "",
    "The unbelievable word association guessing game",
    "Can You Guess NBA Player From The Picture?",
    "Place tiles to make words as the language keeps changing.",
    "Prime Pro-Rhyme Row installment 5. EctoComp Petite Mort.",
    "Захвати планету, пока планета не захватила тебя",
    "",
    "Asteroids and Letters, Oh my!",
    "Explore the wonderful world of poetry through deceptively simple substitutions ciphers",
    "Making Magic Words",
    "Spell words to cast magical spells!",
    "",
    "An early learning game for young readers",
    "A Brand new type of word game that’s more fun, interesting, and humorous than the same old crossword/Sudoku genres.",
    "3D crossword platformer",
    "",
    "It is wordle.",
    "Find three words based on the position of your guess",
    "",
    "Join words to create and cast Spells. Then join those Spells to cast more Spells. Then join THOSE Spells to...",
    "Defeat wave after wave of incoming WORDZ",
    "Educational endless runner ame game with letters",
    "A relaxing word puzzle",
    "",
    "Only one word, only one letter choices",
    "A simple word guessing game in your own pocket!",
    "A drunken robot guessing game based on the expression \"what are you waffling about?\"",
    "",
    "A roguelike word game where writing is fighting. Spell words to fight absurd opponents and evade their devious abilities",
    "3D Spelling Words Game",
    "A game about conversational navigation.",
    "Words are a super-power!",
    "A more difficult, more involved Wordle-like game! Try to jump each Hurdle word as they get closer to you.",
    "Waste some time searching for words!",
    "The Island of the Treasure",
    "Word King 2020 - Word Connect Game",
    "",
    "Make shapes with letters",
    "Scrabble meets Candy Crush",
    "",
    "short german word puzzle jump and run",
    "How many words can you come up with?",
    "Race against the clock to find the words hidden in the grid!",
    "Game SANS TYPO, Kita buat dengan tujuan Edukasi dan melatih skil mengetik.",
    "Shavian word bingo.",
    "",
    "Clone of currently popular word guessing game",
    "A simple but addictive word puzzle game.",
    "A Simple Word game in godot",
    "",
    "BuildGameBlock Game Page",
    "Try to type in as many words that fit one of over 30 prompts!",
    "The PTA has locked you in a dungeon to tone down your humor. Complete puns to escape!",
    "跨过死亡，达成结局。",
    "A Word Forming Constellation Game",
    "Over 350 cryptic idioms to decipher",
    "\"it\"s up to you if \"it\" ends",
    "Obliterate texts using the ULTRA HIGH POWER LASER BLASTER!!!",
    "Decipher the word in the shortest amount of time possible",
    "A game inspired on wordle!",
    "Educational 2D platformer",
    "A game of wit and word mastery",
    "a word vacation for your brain",
    "derived from a blending of two or more distinct forms. Made for GMTK 2021",
    "",
    "The first rule of chain letter jam is: you tell everyone about chain letter jam",
    "Jammin' 4 Jesus!",
    "A collaborative, anonymous, creative writing experiment",
    "A heatwave gets near! AVOID",
    "Your daughter wants to hear a bedtime story",
    "Guess wikipedia page title from its description",
    "A Hangman game using ASCII art and sporting a 415,700-word library for endless play",
    "Le runner qui te permet d'écrire plus vite au clavier !",
    "A new game played with a LetterPress deck",
    "covid-19",
    "Ascii typing game which takes place in the 60s space race era.",
    "Can you call yourself a cricket fan if you can't complete this quiz?",
    "A simple talking to the plant game.",
    "¿será demasiado larga para ti?",
    "stop the apocalypse. 81 12 59 122 124.",
    "4 images composent les ingrédients d' 1 cocktail !  Trouver le !   Jeu codé en 6-8 heures environ...",
    "A mask in world of words",
    "Infinite Runner meets Word Games! Make words, keep running and beat your high score!",
    "Space simulation",
    "Word-Based Puzzle Game Set On a Distant Space Station.",
    "no-signup multiplayer word builder",
    "Occult difficult word building puzzle",
    "A One-Star Reviewing Experience",
    "Brainwash sacrifices by chanting arcane words!",
    "A language learning game where the user paints with words!",
    "A fun online multiplayer build-a-sentence shooter",
    "Protect Earth by negotiating peace with an alien planet.",
    "Welcome, wizard! Are you ready for war?",
    "",
    "Words often hurt more than the mightiest weapon...",
    "Create words to uncover your grave and stop yourself from being buried alive.",
    "",
    "Downloadable for FBLA",
    "Build upon previous words to make new ones!",
    "Fast paced, two player co-op word game!",
    "Fight the Tooth Fairy for your teeth in this brickbreak, spelling adventure!",
    "",
    "space scramble",
    "A Word Game Roguelike",
    "It's like scrabble but you play as the Bag of Tiles",
    "Offend your friends, family and your boss",
    "",
    "Guess the words, make the crystal glow",
    "",
    "A piano repairing puzzler that you can beat without looking at the screen",
    "Puzzle、Word Adventure",
    "Merry Rings",
    "This is a remake of the classic British gameshow Countdown. Play against the computer to find the highest scoring words.",
    "a word based puzzle game",
    "an illustrated  exploration game",
    "Copycat Alpaca Lifeform Prevention And Control Agency: No secret Alpacas, guaranteed!**",
    "Wordle... with a Twist",
    "the Wordle-inspired game that lets you test your vocabulary with words of any length.",
    "A word game",
    "",
    "Our recipe is simple, one Level, one Pizza !!!",
    "Pure words adventure",
    "Can You Guess The Indian Actor &amp; Actress From The Photo?",
    "A certain puzzle game meets a certain word game",
    "Word search game is completely free, created to help kids, students and adults to learn Tamil words in a fun way.",
    "一款单人开发的模拟当代大学生暑假生活的文字策略养成游戏！",
    "",
    "Spell words like your life depends on it",
    "Wordle but no limits and optional algorithm hints",
    "Umaru is thinking of something, can you guess what it is?",
    "",
    "",
    "Two Scrabble-inspired minigames by H.H. Magoo",
    "",
    "",
    "3D Wordle",
    "",
    "Word Connect -Word Puzzle Game.  Brain game for TRUE WORD geniuses!",
    "Solve anagram scrambles to hack the planet!",
    "A free multi-language letter guessing game similar to hangman and wheel of fortune with multiplayer and mod support.",
    "I was bored and wanted a play again button on wordle so I made this.",
    "The whole world's a stage . . . except here, you really are on a stage. Type your way through Shakespeare's best lines!",
    "Erase your enemies' names in this Wordle-like fighting game!",
    "Play as Ratatoskr, the gossip-y messenger of Yggdrasil, whose finest pastime is delivering insults.",
    "Word search game is completely free, created to help  everyone learn English words in a fun way.",
    "Wordle but in Valyrian, the language from Game of Thrones",
    "Explore stories, interact with text, and have fun! Boss battles, collectibles, puzzles, and a song await!",
    "The adventure of a book that must collect the letters of the words in the correct order.",
    "Prefix &amp; Suffix  Save The World",
    "As we name things, so they become...",
    "The Mind Stretching Matching Game",
    "Word search puzzle game using emoji cards",
    "A cute word game with roguelike elements",
    "Match-3 meets word search!",
    "An addicting word-puzzle game like hangman in hard-mode",
    "Make words from words from sentences from paragraphs from...",
    "English word puzzle game",
    "The expanded &amp; enhanced CodeRandom",
    "A difficult isogram-guessing puzzle-word game",
    "Create words from the available letters and get bonuses for completing challenges.",
    "Survival Word Game is a HTML5 CANVAS web based 2d game.",
    "",
    "Roll dice with letters and combine them into words.",
    "Plants vs. Zombies meets Scrabble",
    "Created for the Game Dev TV Game Jam, May 2022",
    "WORDLOS is a clone of the neo classic word game for DOS",
    "a thing about words",
    "",
    "A Controller-Based Multiplayer Typing Game 😳",
    "The ideal initiation video game for preschool children to learn words in English and Spanish.",
    "Use classes de palavras para montar uma pequena história.",
    "Guess the word moving,changing and rotating the cubes to the right position",
    "\"El odio solo nos ha llevado a la destrucción, vivir como hermanos es nuestra única solución”.",
    "The Unique Jigsaw Crossword Puzzle Game!",
    "mixed words is a word game, Find a list of words in the grid.",
    "Mini Jam 110",
    "World Search! A word jumble and crossword mashup! Explore the first 25 levels and more coming soon!",
    "This project looks at the many origins, uses, reclaiming, shaming, and long herstory of the term slut.",
    "a crossword game made in godot",
    "A Falling-Sand Style Game",
    "Terminal Hacking Game with anagrams!",
    "",
    "Türkçe Kelime Bulma Oyunu",
    "Word Guessing Game Based On Isograms",
    "Wordle clone you can play against your friends",
    "Quick-fire anagrams of fish, countries and more!",
    "Older game like Wordle but more pro! Follow the hints and find the hidden word.",
    "A cryptic crossword about code-switching",
    "a completely free wordle-like with online leaderboard",
    "Play my word-making game for free!",
    "An X-Files themed Wordle game!",
    "Hangman meets Platformer. Collide to change char. Die to check. Collect 8 bits to get 1 correct. Random word or Speedrun",
    "Guess what the shuffled word is!",
    "Lumberajck Rossi has to escape from a mysterious world. Will he make it?",
    "Word Game",
    "Are you a real word puzzle game master?",
    "FBLA Video Game for SLC 2022-2023 by Abhijay Venkatesh",
    "How much do you depend on it? What happens if your smartphone gone? Will you feel helpless?",
    "Try to guess the hidden 6 letter word in 5 guesses!",
    "Party games with AI",
    "You love wordgames?!",
    "Game submitted as part of the GMTK 2020 Game Jam",
    "How many words can you make?",
    "LuaMan is a simple console based Hangman-game written only in Lua for the Lua GameJam 2022.",
    "A Book Parody Sorting Puzzle Adventure",
    "Find the lol champions ussing the similarity of their names.",
    "Game Edukasi kata tentang hewan langka di Indonesia",
    "Motorcycle-themed crossword puzzle",
    "A time waster puzzle game.",
    "A word puzzle to combat your boredom and keep you sane!",
    "The classic game of memory mixed with fill in the blank",
    "Wordle like game with music related words",
    "A digital exploration of post vandalism and non-linear storytelling.",
    "Add letters to spell the secret word.",
    "A wordle clone for everyone.",
    "A Pico-8 demake/port of the popular viral word game.",
    "",
    "Efficiently use swaps to make words in this Scrabble-inspired puzzle game",
    "Belajar kosa kata dengan Harry Puter!",
    "Wordel is a very unoriginal take on an original game",
    "play cute hangman with root words!",
    "An unknown facility. a strange situation. and an A.I. with no concept of the 4th wall. what could go wrong?",
    "",
    "Play a draw &amp; guessing game with friends in a beautiful home!",
    "Dive into the ultimate adventure and delve the deepest root with our Global Game Jam 2023 game!",
    "Be aggressively illiterate.",
    "Search for a single word in a word search",
    "Improving your vocabulary and spelling skills during  the gameplay!",
    "A puzzle where you move boxes to form words.",
    "GameDev.tv Game Jam 2022 inspired game.",
    "A sequel of sorts to Very Vile Fairy File.",
    "Build on a new planet by correctly answering random music vocab questions!",
    "Permainan merangkai kata",
    "An \"edu-game\" for learning animal words /s",
    "",
    "In this game, you must walk through invisible mazes, words scrambled beyond belief, and light all the torches",
    "Finish your assignments before the deadline hits!!",
    "",
    "A little game for the GMTK game jam 2021",
    "Start With Nothing",
    "Multiplayer Word Game",
    "Grab beans while you fall and spell words to climb back up!",
    "Juego de palabras",
    "hunt for words in a hexagonal grid",
    "A fun game where you find words",
    "Guess the hidden word with limited lives and with bull-cow counter!",
    "Find the letter, fill the category.",
    "You know the game...",
    "Save Shakespeare's Text!",
    "",
    "",
    "\"We are at the brink of...\"",
    "A hangman with a little twist in it. https://youtu.be/3eAfabnnwF4",
    "A game where you piece together words of 4 letters",
    "try to breed the target word",
    "",
    "Codenames Reimagined as an action packed word puzzle game",
    "Educational platform game",
    "",
    "This simple and fun test will help determine if you are a banana or not",
    "Word Game with a Territory Control Twist",
    "Guess Words from Pictures / 3 GAMES FOR ANDROID!",
    "Surf through the works of Pixar and find their names.",
    "Combines the creativity of word-forming board games with the addictive nature of classic arcade puzzle games!",
    "A typing game written in vanilla JavaScript",
    "UE4 Word guessing game",
    "Think you're clever? Prove it with an enigmatic AI, the ultimate master of riddles beyond imagination.",
    "Terra Incognita FPS RPG",
    "",
    "3h Trijam#177 entry. This is a Word Puzzle game, where you are trying to fing the target in each level",
    "Khusus orang indonesia",
    "Grab your towel and sunblock! It's time to relax by the pool with your friends",
    "",
    "Break_me",
    "An experimental rhythm-edutainment game for building career-focused English grammar, vocabulary and job knowledge!",
    "A short story about a mother who wanted to give her baby away.",
    "Create and then solve your own wordsearch puzzles.",
    "a classic worded rpg game",
    "_ 文 _ 字 · 寻 _ 真 _",
    "Quick-fire anagrams of Pokémon names, transport and more!",
    "Choose your own path in the dark world of Red.",
    "",
    "Word puzzle",
    "Speedy anagram game with online leaderboards.",
    "",
    "Leaf Wordle is one of Erkan Yaprak Games",
    "A short word-puzzle game, that tells a poem in reverse.",
    "A recreation of John Ridley Stroop's \"Stroop Test\"",
    "Welcome to VocaBRAWLary, a fast and fun multiplayer typing game. Compete against your friends to become a Word Master.",
    "",
    "How many words can you create at once by dragging a single tile?",
    "A word based shooter game",
    "what if wordle was nonsensical",
    "Redefine Everything Around You: Using Letters",
    "What happen when space shooter combined with anxiety?",
    "SLime life time money",
    "",
    "A high-low guessing game based on the English language",
    "A spelling bee of geographic locations",
    "不諧無恕，敢諧有你。",
    "",
    "A tribute to Wordle using only german words",
    "",
    "UE4 DEMO",
    "Visual Novel Rebelium menceritakan seorang pemuda yang bingung memilih masa depan antara kuliah, bekerja atau menikah.",
    "Match letters into words and do inventory management to defeat your enemies.",
    "an asynchronous multiplayer spelling battle game",
    "Free Web Browser Word Game",
    "Felfedező-pontgyűjtő szókirakó játék",
    "Have fun playing the classic bubble shooter game while learning new English words and improving your vocabulary skills",
    "Literally Wordle but you get to play it differently!",
    "Neon ball Rolling in neon world",
    "Kelime  avına başla! Yanlış kelimeleri vur!",
    "The Reverse Crossword",
    "A game poem remixing the work of Edwin Morgan",
    "Guess the idiom based off the synonyms!",
    "Drag blocks and make words to achieve High Scores!",
    "String words together from a grid of random letters.",
    "Word fun: Word Puzzle Game with Graphical Elements",
    "Word game with a roll of the dice!",
    "Jokebot 8000 is a sophisticated machine capable of replacing humankind's top comedians.",
    "the Word Tripped then fell",
    "Fast-paced word building",
    "tend a bar of lonely patrons",
    "Cute cookies, classic games! Let's try this unique jigsaw puzzle game for FREE!",
    "iPhone Multiplayer word game",
    "",
    "Serious topics combined with an absurd. Think outside of the box through analogies!",
    "simulation. trolley problem.",
    "Procedurally Generated Crossword Puzzles",
    "",
    "A 5 letter word guessing game",
    "Impress your alien friends with your newfound mastery of English!",
    "How well do you know words that end with the letter \"P\"?",
    "masochistic word game",
    "You're close to the password. Can you solve it?",
    "Have \"fun\" with your friends in this online party game.",
    "Puzzles &amp; Brain Games",
    "Another Wordle clone, this one shows the times a letter exists on the word.",
    "Frantic semantic antics",
    "Can you complete these famous quotes?",
    "Game that my team and I made for FBLA State in 2022 - 23.",
    "A new twist on the word game classics",
    "Short demonstration of Twine",
    "A strategic letter-puzzle game show!",
    "Guess the words or our friend will hate us.",
    "Swiper letters to find word. Easy and endless gameplay",
    "A bullet-hell word game about a Mouse Cursor saving the Internet.",
    "",
    "Keep your flame burning and your ink flowing!",
    "Like wordle but worse!",
    "Decipher the ancient scriptures and finish the sacred ritual.",
    "Press the key you are standing on in order to jump and escape certain doom.",
    "",
    "Guess the name of a game.",
    "A snake game in which you have to form a string of words",
    "top-down shooter, puzzle",
    "",
    "A sweet word game we made!",
    "Boggle meets Match 3",
    "You loved Queen's Gambit, so become the master of the Knight's Moves!",
    "In this Short game, you will learn how to read, listen and DELIVER messages in morse code in under 10 minutes!",
    "Wordle English Game Maker Studio Souce Code",
    "A prototype of the game Wordle, follow our guide to make one yourself!",
    "Name the word that connects to all the clues",
    "Use your Word Creating Wits to Rescue animals in your park.",
    "Popular word game with a new twist",
    "Dice up words and create the requested anagrams",
    "A word puzzle game, use up all your letters in as few words as possible.",
    "Tile and complete the word puzzles with drag and drop unified letters.",
    "Find the colors.",
    "guess the five letter word in five guesses",
    "An Alchemy like puzzle game",
    "",
    "Can You Guess The Player From The Picture?",
    "Fertilize your root with prefixes and suffixes to make your carrot grow!",
    "",
    "",
    "",
    "Defeat the Mad Scientist! Decode passwords under pressure!",
    "Create high scoring words and keep your chickens safe from the hungry foxes!",
    "It's a game where you try to type inverted words correctly.",
    "Fan re-make of discontinued word game, Wordbase",
    "Heart-pounding librarian action",
    "Animal Words is a brain puzzle game.",
    "Word Search powered by ChatGPT and Gamefroot",
    "A unique spin on wordle",
    "",
    "",
    "Clássico jogo da forca com interface moderna (português-BR)",
    "",
    "Build dice by unscrambling 6-letter words.",
    "Untwist the words!",
    "A quantum variant of wordle",
    "Enjoy a music festival.",
    "Word Puzzle Game",
    "Swipe the screen to identify if the words are noun, adjective, verb or adverb.",
    "Play a game as I",
    "MOONSH🌖T is a word making space race",
    "Combine two items to create an idiom",
    "Simple Wordle clone in Godot",
    "Can you spot these spelling abborations",
    "Bullet hell-ish where the speed of your car or the world is affected by the words you create!",
    "",
    "Improvisational Poetry",
    "Guess the name of a film.",
    "a clone of wordle in Pico-8",
    "A fun, addictive and brain stimulating game.",
    "Well.. nearly impossible",
    "Guess the name of a song.",
    "Wordle, but with satisfying animations!",
    "Connect letters together by dragging your finger. Make as many words as you can.",
    "The best party game for group of friends!",
    "",
    "A simple text game made in Unity where you must hack into several locations.",
    "A Kid-friendly Wordle game",
    "A word-matching roguelike experiment.",
    "Insult yourself. Insult your friends. Insult everyone, you failure of a fungus.",
    "A game of finding words from bug-ridden world. Made for Game Off 2021",
    "Submission for WWU GDC JAM Spring 2019",
    "Unscramble jumbled words and collect points",
    "",
    "a 5 letter word game",
    "Small word game written in just 500 characters of HTML/CSS/JavaScript",
    "You and the AI try to guess each other's secret words",
    "A shoot 'em up - word game - hybrid",
    "Solve word puzzles to hack into the mainframe.",
    "​IQ Word Connect is a mobile game app that challenges players to connect a series of letters to form words.",
    "Guess the math equation in 5 tries. A new puzzle is available each day",
    "Definitely not Wordle...  Source Code available in description",
    "🌷 Fais pousser ta fleur pour retrouver la couleur 🌷",
    "The Literature Game Show",
    "Trouves le mot caché par association avec 3 indices !",
    "A multiplayer word game!",
    "Spell words, cast spells, defeat monsters, save the library!!!",
    "",
    "A silly game about making contractions",
    "An action-spelling arcade game where words are weapons",
    "Reflective written nnarrative",
    "Collaborative story-writing mobile game.",
    "Combine adjacent letter-tiles to make compound tiles.",
    "Search word in the automatic generated WordSearch.",
    "Keyboard word game based on key positions",
    "Survive the Zombie Apocalypse",
    "Exploratory word game in crossword style. \"Every word is magical.\"",
    "Multiplayer Coop-game where each player has their own task to survive",
    "",
    "",
    "Collect Alphabet Soup letters to make pop art related words!",
    "A word game where you continuously add letters to spell words.",
    "Word Puzzle, Sudoku, Memory Game, Color Puzzle",
    "A stylish Wordle clone",
    "Challenging words game",
    "Minimalist Word Puzzle",
    "Vocabulary chalenge",
    "Make as many words as you can in a minute.",
    "Intenta Hackear las clases de música para subir tu nota!",
    "",
    "Unscramble the Password &amp; Become the World's Greatest Hacker.",
    "Text based anagram word game for killing ghouls! Are you sick enough in the head to complete these puzzles?",
    "We are the no more than sum of our parts",
    "Your goal is to guess every Celebrity and successfully complete the game.",
    "A knockoff version of the verbal memory game on human benchmark.",
    "Test your English slang from every region of the UK.",
    "Mine the rocks to find word gems!",
    "Fun word puzzle that may or may not be poop themed.",
    "",
    "Defeat Filipino mythical creatures while learning Baybayin!",
    "Get points for making words by changing just one letter of a given word",
    "",
    "Arcticade is a 2D arctic-themed typing game.",
    "A speedrun word game where you have to decipher mangled English in order to procceed!",
    "Foodle is a themed Wordle game that focuses on food. All words guessed must be food related.",
    "Android Game",
    "wordle que eu fiz pra uns amigos jogarem",
    "Typing game where you create loops of words linked by first and last letters.",
    "A Jamaica word game",
    "local, turn-based, 5-to-6-letter, 1v1-style 'wordle' clone",
    "",
    "Slide into casual, fun wordplay",
    "3hr jam game: Create new words by flipping adjacent letters",
    "",
    "A wordle variant for 6 letter words",
    "",
    "",
    "A learning game for children",
    "Unravel the mysteries of space...",
    "A word puzzle",
    "Try to guess your friends' words!",
    "Play as Felix. Spell words. Defeat a prestigious University.",
    "A puzzle game where the pictures represent a hidden word!",
    "Word Quiz where you need to Find Animal names like Cat and Dog",
    "Write as many words as you can in 10 seconds with the locked letter.",
    "Wordle, but with symbols",
    "A vertical word-puzzle game",
    "Duality word game",
    "Find the words",
    "Hack your way through the jumbles.",
    "The show must go on - a blackout cannot stop this small word puzzle game.",
    "Find out what kind of flower you are",
    "A wordle game made with GDevelop",
    "This is a \"hangman-style\" guess the word game",
    "",
    "A ruzzle italian game",
    "A.I. IS HERE. Type to guess the words used to create A.I. artworks.",
    "Guess the blurred letters.",
    "Scrabble en español",
    "Neon ball Rolling in neon world",
    "Permainan Coba Tebak adalah permainan tebak kata dengan pertanyaan yang random.",
    "",
    "",
    "Demo for Interactive Branching Narrative Audiobook Project",
    "Trying to create an unholy combination of Final Fantasy 1 and Scrabble.",
    "A semester of creative writing and answers at Stony Brook University",
    "Addicting and Fun Word Puzzle Game!",
    "Use letter tiles to help solve the crossword puzzle",
    "Easy to learn, tough to master.",
    "connect the words",
    "20 seconds to speed-solve pre-guessed Wordles!",
    "",
    "Help Connect Patrons to Art at Your Gallery's Latest Show Opening!",
    "A simple text-based/dev-graphic anagram guessing game.",
    "Spelling and creature collecting on Android!",
    "7-letter word-guessing game",
    "Word search game where you have to form words from 7 letters.",
    "Girls night gone wild when you have to figure out how to calm down your friends enough for you to get out alive.",
    "A puzzle combined with 2D adventure game, the player need to think out of the box, and form new ability.",
    "Shoot the letter and solve the phrase but you better hurry before time runs out and...",
    "Pair game with word mode!",
    "Wuzzles to exercise you mind. The pictures depict words, phrase or saying.",
    "",
    "A brain on fire word puzzle game, a mix of wordle and tetris",
    "",
    "В этой игре нужно работать сообща, чтобы вычислить притворщика",
    "Challenging, fun, developer and thought-provoking word game.",
    "Keep the mallow from burning.",
    "A game prototype",
    "crossword puzzle maker game",
    "A small test build of a higher/lower word finding game, inspired by wordle but different.",
    "It hates you",
    "A short text based puzzle game in which you must find Hidden Words.",
    "Word Explorer - You can train your brain as you make words.",
    "Guess all the words!",
    "Projeto TCC de ADS",
    "Classic Logic game \"Bulls and Cows\" on a whole new level. Just guess 4 numbers in the right order.",
    "Text Twist in Android using Java",
    "El ahorcado, Disfruta esta versión versión, también conocido como “colgado”.",
    "Word Ladder meets Rubik's Slide puzzle",
    "",
    "",
    "Ты — охотник за головами. Он твоя цель и ты нашёл его.",
    "Yo-ho-ho~~ cross words and bomb your enemy to feed the fish ~",
    "A word juggling puzzle game",
    "Given 3 challenge words, select the correct sound coin. Alliteration is key!",
    "PEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEP",
    "Arma palabras usando Silabas",
    "A casual android game where you search for words in a particular category",
    "Idea for a prototype minigame for Typing Bullets (a proto-type)",
    "Class Pledge Game",
    "A word based adventure rpg game where your choice decides your fate.",
    "Just swipe and match letters to meaningful words. Train your brain, test your memory.",
    "How many Bible icons will you guess before the time runs out?",
    "Train your brain with a new word puzzle! Slide rows &amp; columns to find words.",
    "Adivina la palabra secreta en 6 intentos o menos.",
    "Change only one letter per guess to get to the end word",
    "Hangman in english",
    "Choose the seashell that rhymes with the word on the coin!",
    "",
    "A word puzzle game",
    "",
    "Simple word puzzle game",
    "",
    "",
    "Choose whether the word given uses a short or long vowel!",
    "A simple learning game that was made to help kids learn hebrew.",
    "A simple yet challenging ridles game that tricks your brain",
    "Para android- for android",
    "Fun word game",
    "",
    "An Angram Solving Adventure",
    "Speed typing game this is the premium version without advertising and 3 lives.",
    "New puzze game mechanics. Can you collect all the words? Can you do it faster than others",
    "Learn new vocabulary simply by connecting puzzle pieces",
    "2D Game Project for Game Programming Assignment 2022 Spring - TAMUCC",
    "A tiny word game inspired by NYT's Spelling Bee",
    "Play the classic children's game with your chat!",
    "Given a challenge word, select the correct word coin. Alliteration is key!",
    "Just  a wonderfully whimsical way to wonder with words",
    "Enjoy a different kind of word game. With this new two stage Safari into the World of Words!!!",
    "One or two player word game",
    "A clone of Wordle that allows you to make your own puzzles",
    "",
    "simple word puzzle",
    "Battle Friends with Words",
    "Command your army with the power of rhythm and typing",
    "Leaf Wordle is one of Erkan yaprak games",
    "Make new words by switching different phonemes!",
    "Test your knowledge! Guess the car image",
    "words from one word",
    "Minimal word unscrambling",
    "",
    "",
    "Forme palavras e faça o máximo de pontos que puder!",
    "Classic Word Search Game with exciting rewards",
    "An attempt to clone wordtwist/text twist (who remembers that game?)",
    "",
    "ACTION SPELLING",
    "",
    "",
    "Guess the word in six tries.",
    "",
    "sharpen your brain with fun word games",
    "a relaxing word game",
    "A Game About Anagrams",
    "",
    "little word shifting game",
    "Попробуй найти все слова!",
    "Explore your vocabulary range by playing this mini-game where you write words that contain two letters as shown",
    "This quiz game is a great choice when you want to learn something...",
    "",
    "A game about twisting and reversing characters",
    "Build words using phonemes and help Darwin the gorilla cross the river!",
    "De-scramble the words before the timer runs out!",
    "Photo Quiz - Animals - See the image and guess the word! Guess The Picture will entertain you for hours!",
    "You can now play Word Mania Guess! Do you know your words?",
    "Game android simpel dalam menebak kata",
    "It never ends",
    "Scrabble meets pong.",
    "Dicey Words is a fun and challenging game of strategy and chance.",
    "Welcome to the world of words! Find the hidden words !!",
    "Ethiopian Amharic Language Word Create Mobile Game",
    "This fast-paced word game is a test on anybody's vocabulary",
    "Word search game is completely free, created to help kids, students and adults to learn Hindi words in a fun way.",
    "Daily Word Puzzle",
    "",
    "It is a beautiful app half Quiz and half puzzle",
    "Classic Wordle game in a new setting.",
    "",
    "Train your brain and learn new words by solving guessing the pics.",
    "Game we all know, adapted for covid times.",
    "Beautiful Quiz game.",
    "WordAABC search 0.1.0",
    "App with collection of short stories, trivia and games.",
    "​Play through the hurdles of football trivia question and be a champ! The ultimate game for football enthusiasts.",
    "Hangman with a silly twist",
    "Train your brain and learn new words by solving guessing the pics.",
    "",
    "A retro epic murder mystery adventure game steeped in Irish history, mythology and politics.",
    "Jeux du pendu en français",
    "FBLA 2023",
    "",
    "",
    "Pentrado - Draw and Guess in Your Own Language",
    "WordIt: Improve your vocabulary with fun",
    "Difficult word puzzle with retro graphics",
    "A well known game on making words.",
    "An open source word guessing game with fully customizable entries",
    "Guess The Word",
    "",
    "বাংলা ভাষার ওয়ার্ডল",
    "Æxpression is new kind of RPG Fantasy Game where you won't go far with only smashing your head on the keyboard.",
    "Fun word creation!",
    "Pave your way through the levels and get engaged in a world of fun and thinking!",
    "Meme Based Game",
    "flappy words",
    "Word Royal  is a game that will make your brain think carefully and create words out of letters that will be entered",
    "A replica of the popular daily word game Wordle, with unlimited playability.",
    "Wordle with custom word lists you can share.",
    "A text based fishing game",
    "",
    "can you complete it with no raging?",
    "",
    "English Word Game",
    "Sammy the Runner fun and mind changing and more challenging",
    "Adlib, an adlib game by Blaze Games",
    "searching for words",
    "THIS IS A GAME OF RACE",
    "Game to match greek words to english words from bible",
    "Made for Summer Slow Jams August 2019: Edutainment Games​ - Theme - Ancient History",
    "",
    "Train your brain and vocabulary with the brand new word search game!",
    "A typing game with combos and explosions",
    "A thrilling, interactive, choose-your-own-adventure-style, narrative fiction game.",
    "Find out what your friends think about Utopia through simple bingo game",
    "Wordle Türkçe Sınırsız Oynama Hakkı",
    "Mini version of the game \"Wheel of Fortune\"",
    "Innovative Game to improve Vocabulary, Spelling, Language and Education",
    "An word game about learning Baybayin",
    "Rearrange the words to progress, three different games and gets more difficult!",
    "Brain teasers/puzzle  game",
    "",
    "A WORD GAME FOR DISRUPTORS!",
    "",
    "Think You're Awesome? Try This Game !",
    "Hack into 3 locations",
    "funny hangman style game",
    "My First Ever Indie Developed Game, is an Old Style Hacking game.",
    "",
    "",
    "matching",
    "Challenge your brain with over 300 levels, each more difficult than the last",
    "A game I made following the Gamedev.tv Unreal Engine C++ Course.",
    "Endless Runner",
    "Mix of crossword puzzles and hangman, where you will have to guess the words, which you will love.",
    "Word Guessing Game",
    "Intellectual game in which you have to make a word from the letters on the field.",
    "",
    "A game about what you need to do to win.",
    "A  2 player PC Java word game where letters are shot and words are won",
    "shoot with words",
    "Reveal a hidden quote",
    "Bigger letter, slight bright, berime time, and still in beta!",
    "A Missing Spelling Word Trivia game for PC/Desktop to increase Vocabulary and Memory.",
    "Help power Weego in his adventure to the party by collecting letters and building words.",
    "Cloze Test",
    "Think fast! You have 30 seconds, see how many words you can can think off under pressure",
    "Word Puzzle Decoration Game",
    "a game like word of wonders",
    "",
    "Guess isograms (words with no duplication of letters) for fun and profit. Well, one out of two, isn't bad!",
    "Take an obscure japanese game called Blocksum and make it about words",
    "Build and complete English Sentences",
    "A fun little game about learning some bones in the human skeleton.",
    "guessing two words at once? sounds rough.",
    "A prototype snake word game.",
    "",
    "",
    "One-button autoscrolling vocabulary shooter.",
    "Use your spelling skills with strategic use of special tiles to beat the clock and advance to the next level!",
    "",
    "A vocabulary challenge game made in 3 hours for TriJam #57.",
    "Tetris with words"
]
