from splinter import Browser
import sys
import random
import string
import time

class UploadSU(object):
	urls = [
	    # "http://www.addictingwordgames.com",
	 #    "http://www.addictingwordgames.com/games/1-word-10-tries",
		# "http://www.addictingwordgames.com/games/10-letter-words",
		# "http://www.addictingwordgames.com/games/2-3-4-letter-words",
		# "http://www.addictingwordgames.com/games/2009-paris-fashion-show",
		# "http://www.addictingwordgames.com/games/4-letter-word-bnc",
		# "http://www.addictingwordgames.com/games/60-second-word-search",
		# "http://www.addictingwordgames.com/games/60-second-word-search---hungarian-edition",
		# "http://www.addictingwordgames.com/games/airport-word-search",
		# "http://www.addictingwordgames.com/games/alpha-catcher",
		# "http://www.addictingwordgames.com/games/alpha-soup",
		# "http://www.addictingwordgames.com/games/alphabenz",
		# "http://www.addictingwordgames.com/games/alphabetic-hail",
		# "http://www.addictingwordgames.com/games/alphabetics-orbs",
		# "http://www.addictingwordgames.com/games/alphabits-scramble",
		# "http://www.addictingwordgames.com/games/alphabots",
		# "http://www.addictingwordgames.com/games/ambigram",
		# "http://www.addictingwordgames.com/games/ambiguity-plus",
		# "http://www.addictingwordgames.com/games/anagram-escape",
		# "http://www.addictingwordgames.com/games/anagrams",
		# "http://www.addictingwordgames.com/games/angry-pig-typing",
		# "http://www.addictingwordgames.com/games/animal-kingdom",
		# "http://www.addictingwordgames.com/games/animal-word-scramble",
		# "http://www.addictingwordgames.com/games/animals",
		# "http://www.addictingwordgames.com/games/arthropoda-search",
		# "http://www.addictingwordgames.com/games/asteroid-defense",
		# "http://www.addictingwordgames.com/games/astronaut-word-search",
		# "http://www.addictingwordgames.com/games/b-hangman",
		# "http://www.addictingwordgames.com/games/b-speed-typer",
		# "http://www.addictingwordgames.com/games/b-speed-typer-ii",
		# "http://www.addictingwordgames.com/games/b-speed-typer-iii",
		# "http://www.addictingwordgames.com/games/b-word-challenge",
		# "http://www.addictingwordgames.com/games/babble",
		# "http://www.addictingwordgames.com/games/backpack-travels",
		# "http://www.addictingwordgames.com/games/ball-prep-makeover",
		# "http://www.addictingwordgames.com/games/banana-breakers",
		# "http://www.addictingwordgames.com/games/baseball-word-search",
		# "http://www.addictingwordgames.com/games/basketball-word-search",
		# "http://www.addictingwordgames.com/games/battle-scribes",
		# "http://www.addictingwordgames.com/games/bescrambled",
		# "http://www.addictingwordgames.com/games/best-typing",
		# "http://www.addictingwordgames.com/games/blackboard-typing",
		# "http://www.addictingwordgames.com/games/blocktion",
		# "http://www.addictingwordgames.com/games/bloody-hangman",
		# "http://www.addictingwordgames.com/games/bodywords-scramble",
		# "http://www.addictingwordgames.com/games/bolly-word",
		# "http://www.addictingwordgames.com/games/bomb-typing",
		# "http://www.addictingwordgames.com/games/bomber-jack",
		# "http://www.addictingwordgames.com/games/bookstories",
		# "http://www.addictingwordgames.com/games/bouncing-letters",
		# "http://www.addictingwordgames.com/games/bouncing-letters",
		# "http://www.addictingwordgames.com/games/bowling-word-search",
		# "http://www.addictingwordgames.com/games/brick-word",
		# "http://www.addictingwordgames.com/games/british-cities",
		# "http://www.addictingwordgames.com/games/bubble-typing",
		# "http://www.addictingwordgames.com/games/bubble-wordsearch",
		# "http://www.addictingwordgames.com/games/bubbletters",
		# "http://www.addictingwordgames.com/games/bubblingo",
		# "http://www.addictingwordgames.com/games/bumper-stumpers",
		# "http://www.addictingwordgames.com/games/bus-typing",
		"http://www.addictingwordgames.com/games/candy-word-search",
		"http://www.addictingwordgames.com/games/canufit",
		"http://www.addictingwordgames.com/games/capital-tower-defense",
		"http://www.addictingwordgames.com/games/cartoon-words",
		"http://www.addictingwordgames.com/games/casebreaker",
		"http://www.addictingwordgames.com/games/celebrities-word-game",
		"http://www.addictingwordgames.com/games/chain-master",
		"http://www.addictingwordgames.com/games/chainz",
		"http://www.addictingwordgames.com/games/childrens-logic",
		"http://www.addictingwordgames.com/games/chirstmas-word-search",
		"http://www.addictingwordgames.com/games/christmas-treats",
		"http://www.addictingwordgames.com/games/christmas-word-finders",
		"http://www.addictingwordgames.com/games/christmas-word-search",
		"http://www.addictingwordgames.com/games/christmas-word-search",
		"http://www.addictingwordgames.com/games/cinderella-wordsearch",
		"http://www.addictingwordgames.com/games/circus-word-search",
		"http://www.addictingwordgames.com/games/city-of-words",
		"http://www.addictingwordgames.com/games/clockwords-act-i",
		"http://www.addictingwordgames.com/games/clockwords-prelude",
		"http://www.addictingwordgames.com/games/clothing-scramble",
		"http://www.addictingwordgames.com/games/clueless-crossword",
		"http://www.addictingwordgames.com/games/cocktail-sparkles-beauty-makeover",
		"http://www.addictingwordgames.com/games/code-quest",
		"http://www.addictingwordgames.com/games/coin-typing",
		"http://www.addictingwordgames.com/games/colour-balls",
		"http://www.addictingwordgames.com/games/colour-trap",
		"http://www.addictingwordgames.com/games/comet-busters",
		"http://www.addictingwordgames.com/games/compound-letters",
		"http://www.addictingwordgames.com/games/countries",
		"http://www.addictingwordgames.com/games/cowboy-word-search",
		"http://www.addictingwordgames.com/games/cross-7",
		"http://www.addictingwordgames.com/games/crossword-ninja-cat",
		"http://www.addictingwordgames.com/games/crossword-puzzle",
		"http://www.addictingwordgames.com/games/crossword-scramble",
		"http://www.addictingwordgames.com/games/cube-crash-wordz",
		"http://www.addictingwordgames.com/games/cupid-typing",
		"http://www.addictingwordgames.com/games/cupid-typing-2",
		"http://www.addictingwordgames.com/games/custom-word-search",
		"http://www.addictingwordgames.com/games/custom-word-search-vol-2",
		"http://www.addictingwordgames.com/games/cypher-five",
		"http://www.addictingwordgames.com/games/dates-scrmable-words",
		"http://www.addictingwordgames.com/games/december-21",
		"http://www.addictingwordgames.com/games/delicious-lasagna",
		"http://www.addictingwordgames.com/games/demi-tuhan-wars",
		"http://www.addictingwordgames.com/games/deword",
		"http://www.addictingwordgames.com/games/dewordeca",
		"http://www.addictingwordgames.com/games/dinosaur-word-search",
		"http://www.addictingwordgames.com/games/ditloid",
		"http://www.addictingwordgames.com/games/dooma",
		"http://www.addictingwordgames.com/games/dragon-word-search",
		"http://www.addictingwordgames.com/games/drop-a-block",
		"http://www.addictingwordgames.com/games/easter-bunnies-typing",
		"http://www.addictingwordgames.com/games/easy-words-scramble-1",
		"http://www.addictingwordgames.com/games/easy-words-scramble-2",
		"http://www.addictingwordgames.com/games/ego-hangman",
		"http://www.addictingwordgames.com/games/electro",
		"http://www.addictingwordgames.com/games/empathy",
		"http://www.addictingwordgames.com/games/extreme-crossword-2",
		"http://www.addictingwordgames.com/games/fabulous-makeover-diva-style",
		"http://www.addictingwordgames.com/games/face-eater-typing",
		"http://www.addictingwordgames.com/games/fairy-magic",
		"http://www.addictingwordgames.com/games/family-guy-solitaire",
		"http://www.addictingwordgames.com/games/farm-animals-word-search",
		"http://www.addictingwordgames.com/games/farm-word-search",
		"http://www.addictingwordgames.com/games/fast-food-word-search",
		"http://www.addictingwordgames.com/games/fast-typing",
		"http://www.addictingwordgames.com/games/find-that-animal",
		"http://www.addictingwordgames.com/games/find-words",
		"http://www.addictingwordgames.com/games/finda-word",
		"http://www.addictingwordgames.com/games/fish-and-words",
		"http://www.addictingwordgames.com/games/fishaword",
		"http://www.addictingwordgames.com/games/flabberblast",
		"http://www.addictingwordgames.com/games/fleep",
		"http://www.addictingwordgames.com/games/flower-word-search",
		"http://www.addictingwordgames.com/games/food-for-thought",
		"http://www.addictingwordgames.com/games/foods-scramble",
		"http://www.addictingwordgames.com/games/football-word-search",
		"http://www.addictingwordgames.com/games/found-ghastly-language",
		"http://www.addictingwordgames.com/games/free-words-by-flashgamesfancom",
		"http://www.addictingwordgames.com/games/fruit-swordman-typing",
		"http://www.addictingwordgames.com/games/fruit-swordman-typing-2",
		"http://www.addictingwordgames.com/games/fruits-typing",
		"http://www.addictingwordgames.com/games/fruits-word-scramble",
		"http://www.addictingwordgames.com/games/fuseword",
		"http://www.addictingwordgames.com/games/galactic-word-war",
		"http://www.addictingwordgames.com/games/galax",
		"http://www.addictingwordgames.com/games/galgenmaennchen",
		"http://www.addictingwordgames.com/games/gems-typing",
		"http://www.addictingwordgames.com/games/ghost",
		"http://www.addictingwordgames.com/games/gone-fishing-word-search",
		"http://www.addictingwordgames.com/games/grammar-bee",
		"http://www.addictingwordgames.com/games/gravitoons",
		"http://www.addictingwordgames.com/games/greek-legends-nous",
		"http://www.addictingwordgames.com/games/guess-it",
		"http://www.addictingwordgames.com/games/guess-the-words",
		"http://www.addictingwordgames.com/games/guess-what",
		"http://www.addictingwordgames.com/games/gunman-typing",
		"http://www.addictingwordgames.com/games/halloween-hangman",
		"http://www.addictingwordgames.com/games/halloween-treats",
		"http://www.addictingwordgames.com/games/halloween-word-dig",
		"http://www.addictingwordgames.com/games/halloween-word-scramble",
		"http://www.addictingwordgames.com/games/halloween-word-search",
		"http://www.addictingwordgames.com/games/halloween-word-search",
		"http://www.addictingwordgames.com/games/hang-a-bot-state-capitals",
		"http://www.addictingwordgames.com/games/hang-em-high",
		"http://www.addictingwordgames.com/games/hangman",
		"http://www.addictingwordgames.com/games/hangman",
		"http://www.addictingwordgames.com/games/hangman",
		"http://www.addictingwordgames.com/games/hangman",
		"http://www.addictingwordgames.com/games/hangman",
		"http://www.addictingwordgames.com/games/hangman",
		"http://www.addictingwordgames.com/games/hangman-3-languages",
		"http://www.addictingwordgames.com/games/hangman-classic",
		"http://www.addictingwordgames.com/games/hangman-pirate",
		"http://www.addictingwordgames.com/games/hangman-puzzle-game",
		"http://www.addictingwordgames.com/games/hangmas",
		"http://www.addictingwordgames.com/games/hangword",
		"http://www.addictingwordgames.com/games/hardest-typing",
		"http://www.addictingwordgames.com/games/hero-word-search",
		"http://www.addictingwordgames.com/games/hex-words",
		"http://www.addictingwordgames.com/games/hex-words",
		"http://www.addictingwordgames.com/games/hidden-words",
		"http://www.addictingwordgames.com/games/horse-racing-typing",
		"http://www.addictingwordgames.com/games/horse-racing-typing-2",
		"http://www.addictingwordgames.com/games/hospital-word-scramble",
		"http://www.addictingwordgames.com/games/hot-balloon-typing",
		"http://www.addictingwordgames.com/games/humpty",
		"http://www.addictingwordgames.com/games/insect-word-search",
		"http://www.addictingwordgames.com/games/isogram-puzzle",
		"http://www.addictingwordgames.com/games/itsy-bitsy-spider",
		"http://www.addictingwordgames.com/games/jigsaw-open-top",
		"http://www.addictingwordgames.com/games/jigsaw-sunlit-buddah",
		"http://www.addictingwordgames.com/games/jigsaw-zebra-stripes",
		"http://www.addictingwordgames.com/games/jobs-word-scrambles",
		"http://www.addictingwordgames.com/games/jumble-jong",
		"http://www.addictingwordgames.com/games/jumble-laya",
		"http://www.addictingwordgames.com/games/kanji-memory-game-pro-edition",
		"http://www.addictingwordgames.com/games/kekata",
		"http://www.addictingwordgames.com/games/kids-first-play",
		"http://www.addictingwordgames.com/games/knights",
		"http://www.addictingwordgames.com/games/kot-word-search",
		"http://www.addictingwordgames.com/games/lateral---the-word-association-game",
		"http://www.addictingwordgames.com/games/learning-spanish",
		"http://www.addictingwordgames.com/games/letter-blocks",
		"http://www.addictingwordgames.com/games/letter-blocks",
		"http://www.addictingwordgames.com/games/letter-matrix",
		"http://www.addictingwordgames.com/games/letter-rip",
		"http://www.addictingwordgames.com/games/letter-scramble",
		"http://www.addictingwordgames.com/games/letter-twist",
		"http://www.addictingwordgames.com/games/letter-weave",
		"http://www.addictingwordgames.com/games/letters-3d",
		"http://www.addictingwordgames.com/games/letters-catch",
		"http://www.addictingwordgames.com/games/lightning-typing-2",
		"http://www.addictingwordgames.com/games/lightning-typing-3",
		"http://www.addictingwordgames.com/games/lilei-and-hanmeimei-typing",
		"http://www.addictingwordgames.com/games/linguistics",
		"http://www.addictingwordgames.com/games/linked",
		"http://www.addictingwordgames.com/games/lion-typing",
		"http://www.addictingwordgames.com/games/little-red-riding-hood-wordsearch",
		"http://www.addictingwordgames.com/games/logoleptic",
		"http://www.addictingwordgames.com/games/logophobia",
		"http://www.addictingwordgames.com/games/lotus-hall-room-escape-game",
		"http://www.addictingwordgames.com/games/love-word-scrambler",
		"http://www.addictingwordgames.com/games/lunchbreak",
		"http://www.addictingwordgames.com/games/magic-forest-puzzle",
		"http://www.addictingwordgames.com/games/magic-words",
		"http://www.addictingwordgames.com/games/makeup-word-search",
		"http://www.addictingwordgames.com/games/mancala",
		"http://www.addictingwordgames.com/games/mantra",
		"http://www.addictingwordgames.com/games/meaning-fall",
		"http://www.addictingwordgames.com/games/mick-letterton",
		"http://www.addictingwordgames.com/games/million-dollar-words---halloween-edition",
		"http://www.addictingwordgames.com/games/million-dollar-words---november-archive",
		"http://www.addictingwordgames.com/games/mind-flipper",
		"http://www.addictingwordgames.com/games/missed-letter",
		"http://www.addictingwordgames.com/games/mixed-words",
		"http://www.addictingwordgames.com/games/monkeyboard",
		"http://www.addictingwordgames.com/games/monster-word-search",
		"http://www.addictingwordgames.com/games/multiplayer-8ball-pool",
		"http://www.addictingwordgames.com/games/muscle-word-worm-shuffle",
		"http://www.addictingwordgames.com/games/music-word-search",
		"http://www.addictingwordgames.com/games/must-pop-words",
		"http://www.addictingwordgames.com/games/mustache-slap",
		"http://www.addictingwordgames.com/games/my-word",
		"http://www.addictingwordgames.com/games/mystery-words",
		"http://www.addictingwordgames.com/games/mystic-river",
		"http://www.addictingwordgames.com/games/mystic-words",
		"http://www.addictingwordgames.com/games/new-romantic-scramble",
		"http://www.addictingwordgames.com/games/newspuzzles",
		"http://www.addictingwordgames.com/games/nfl-typing-2",
		"http://www.addictingwordgames.com/games/ninja-cat-and-zombie-dinosaurs",
		"http://www.addictingwordgames.com/games/ninja-word-search",
		"http://www.addictingwordgames.com/games/north-korea--launch-typing",
		"http://www.addictingwordgames.com/games/number-riddle",
		"http://www.addictingwordgames.com/games/ocean-word-search",
		"http://www.addictingwordgames.com/games/onomastica",
		"http://www.addictingwordgames.com/games/palindromes",
		"http://www.addictingwordgames.com/games/pantechnicon-connection",
		"http://www.addictingwordgames.com/games/parking-wordsearch",
		"http://www.addictingwordgames.com/games/party-glamour-makeover",
		"http://www.addictingwordgames.com/games/patchword",
		"http://www.addictingwordgames.com/games/patchwork-lite-pt-br",
		"http://www.addictingwordgames.com/games/patchwork-lite-us-en",
		"http://www.addictingwordgames.com/games/phrase-crazy",
		"http://www.addictingwordgames.com/games/piano-typing",
		"http://www.addictingwordgames.com/games/pick-up-strings",
		"http://www.addictingwordgames.com/games/picture-vocabulary-test",
		"http://www.addictingwordgames.com/games/pirate-word-search",
		"http://www.addictingwordgames.com/games/plant-madness",
		"http://www.addictingwordgames.com/games/pollinator-puzzle",
		"http://www.addictingwordgames.com/games/pop-star-word-search",
		"http://www.addictingwordgames.com/games/pretty-chic-girl-makeover",
		"http://www.addictingwordgames.com/games/princess-word-search",
		"http://www.addictingwordgames.com/games/puppet-theatre---mystical-example",
		"http://www.addictingwordgames.com/games/puzzwords",
		"http://www.addictingwordgames.com/games/quarkstar-typing",
		"http://www.addictingwordgames.com/games/quickpick",
		"http://www.addictingwordgames.com/games/qwerty-space",
		"http://www.addictingwordgames.com/games/ramble-scramble---come2play",
		"http://www.addictingwordgames.com/games/random-word-scramble",
		"http://www.addictingwordgames.com/games/random-word-unscramble",
		"http://www.addictingwordgames.com/games/rapperzapper",
		"http://www.addictingwordgames.com/games/rebus-2",
		"http://www.addictingwordgames.com/games/recite-chinese-word",
		"http://www.addictingwordgames.com/games/red-carpet-star-search",
		"http://www.addictingwordgames.com/games/redbeards-treasure",
		"http://www.addictingwordgames.com/games/reggie-red-fur",
		"http://www.addictingwordgames.com/games/reincarnations-awakening",
		"http://www.addictingwordgames.com/games/reincarnations-awakening-chapter-1",
		"http://www.addictingwordgames.com/games/relationship-words",
		"http://www.addictingwordgames.com/games/rhymetime",
		"http://www.addictingwordgames.com/games/riff-raff",
		"http://www.addictingwordgames.com/games/rise-and-fall",
		"http://www.addictingwordgames.com/games/roboflu",
		"http://www.addictingwordgames.com/games/rock-band-word-search",
		"http://www.addictingwordgames.com/games/rocket-typing",
		"http://www.addictingwordgames.com/games/rocket-typing-2",
		"http://www.addictingwordgames.com/games/rocket-writer",
		"http://www.addictingwordgames.com/games/rowowor",
		"http://www.addictingwordgames.com/games/safari-word-search",
		"http://www.addictingwordgames.com/games/save-me",
		"http://www.addictingwordgames.com/games/save-pandus",
		"http://www.addictingwordgames.com/games/save-the-girl",
		"http://www.addictingwordgames.com/games/save-the-monkey",
		"http://www.addictingwordgames.com/games/school-word-search",
		"http://www.addictingwordgames.com/games/scramble-words-creatures",
		"http://www.addictingwordgames.com/games/scribble",
		"http://www.addictingwordgames.com/games/scrimble",
		"http://www.addictingwordgames.com/games/scroll-block",
		"http://www.addictingwordgames.com/games/sea-star-scramble",
		"http://www.addictingwordgames.com/games/sea-typing",
		"http://www.addictingwordgames.com/games/search-the-sand",
		"http://www.addictingwordgames.com/games/semantic-wars",
		"http://www.addictingwordgames.com/games/sensational-wedding-makeover",
		"http://www.addictingwordgames.com/games/shark-antennas-co",
		"http://www.addictingwordgames.com/games/shooting-manish",
		"http://www.addictingwordgames.com/games/shooting-typing",
		"http://www.addictingwordgames.com/games/shootwords",
		"http://www.addictingwordgames.com/games/shrimp-bruschetta",
		"http://www.addictingwordgames.com/games/skater-word-search",
		"http://www.addictingwordgames.com/games/skedaddle",
		"http://www.addictingwordgames.com/games/sky-banner",
		"http://www.addictingwordgames.com/games/skyline",
		"http://www.addictingwordgames.com/games/sleeping-beauty-wordsearch",
		"http://www.addictingwordgames.com/games/slidoword",
		"http://www.addictingwordgames.com/games/slippery-words---little-red-riding-hood",
		"http://www.addictingwordgames.com/games/smily-word-builder-games",
		"http://www.addictingwordgames.com/games/snail-invasion",
		"http://www.addictingwordgames.com/games/snail-invasion-extended",
		"http://www.addictingwordgames.com/games/snakes-n-letters",
		"http://www.addictingwordgames.com/games/snappy-1up",
		"http://www.addictingwordgames.com/games/snappy-2up",
		"http://www.addictingwordgames.com/games/snow-typer",
		"http://www.addictingwordgames.com/games/snow-typing",
		"http://www.addictingwordgames.com/games/snow-words",
		"http://www.addictingwordgames.com/games/snowboard-word-search",
		"http://www.addictingwordgames.com/games/soccer-word-search",
		"http://www.addictingwordgames.com/games/solar-system-word-search",
		"http://www.addictingwordgames.com/games/solo-words",
		"http://www.addictingwordgames.com/games/soul-pawnshop-escape",
		"http://www.addictingwordgames.com/games/space-invader",
		"http://www.addictingwordgames.com/games/space-words-recharged",
		"http://www.addictingwordgames.com/games/space-words-scramble",
		"http://www.addictingwordgames.com/games/spacetrace",
		"http://www.addictingwordgames.com/games/speed-spell",
		"http://www.addictingwordgames.com/games/speedwords",
		"http://www.addictingwordgames.com/games/spell-fest",
		"http://www.addictingwordgames.com/games/spell-words",
		"http://www.addictingwordgames.com/games/spelling-drill",
		"http://www.addictingwordgames.com/games/spelling-kitty",
		"http://www.addictingwordgames.com/games/spicy-snail-foods",
		"http://www.addictingwordgames.com/games/spooky-find",
		"http://www.addictingwordgames.com/games/sports-word-search",
		"http://www.addictingwordgames.com/games/sports-wordsearch",
		"http://www.addictingwordgames.com/games/starmageddon",
		"http://www.addictingwordgames.com/games/stick-ryu-typing",
		"http://www.addictingwordgames.com/games/summer-typing",
		"http://www.addictingwordgames.com/games/supermodel-word-search",
		"http://www.addictingwordgames.com/games/swap",
		"http://www.addictingwordgames.com/games/swappign",
		"http://www.addictingwordgames.com/games/swizzled",
		"http://www.addictingwordgames.com/games/swizzlepop",
		"http://www.addictingwordgames.com/games/swizzlepop---whirled",
		"http://www.addictingwordgames.com/games/synonymous",
		"http://www.addictingwordgames.com/games/szvadsz",
		"http://www.addictingwordgames.com/games/target-words",
		"http://www.addictingwordgames.com/games/taxicab-word-search",
		"http://www.addictingwordgames.com/games/teach-bolly",
		"http://www.addictingwordgames.com/games/terminacore",
		"http://www.addictingwordgames.com/games/tetword-pro",
		"http://www.addictingwordgames.com/games/textmate",
		"http://www.addictingwordgames.com/games/thanksgiving-word-scamble",
		"http://www.addictingwordgames.com/games/thanksgiving-word-search",
		"http://www.addictingwordgames.com/games/that-word-game",
		"http://www.addictingwordgames.com/games/the-amazing-puzzle-factory",
		"http://www.addictingwordgames.com/games/the-apiculturists-laboratory",
		"http://www.addictingwordgames.com/games/the-apothecarys-cellar",
		"http://www.addictingwordgames.com/games/the-britney-apocalypse",
		"http://www.addictingwordgames.com/games/the-crossword-game-v10",
		"http://www.addictingwordgames.com/games/the-fly-typing",
		"http://www.addictingwordgames.com/games/the-gardener",
		"http://www.addictingwordgames.com/games/the-hanged-man",
		"http://www.addictingwordgames.com/games/the-hanged-man-2",
		"http://www.addictingwordgames.com/games/the-random-test-i",
		"http://www.addictingwordgames.com/games/the-stairway",
		"http://www.addictingwordgames.com/games/the-stairway-mobile",
		"http://www.addictingwordgames.com/games/the-time-trap",
		"http://www.addictingwordgames.com/games/the-tortoise-and-the-hare---wordsearch",
		"http://www.addictingwordgames.com/games/the-typing-of-the-ghosts",
		"http://www.addictingwordgames.com/games/the-wizards-notebook",
		"http://www.addictingwordgames.com/games/the-word-factory",
		"http://www.addictingwordgames.com/games/the-word-pyramid",
		"http://www.addictingwordgames.com/games/the-wordies",
		"http://www.addictingwordgames.com/games/toootem",
		"http://www.addictingwordgames.com/games/top-cards",
		"http://www.addictingwordgames.com/games/tropical-mix-game",
		"http://www.addictingwordgames.com/games/truhangman",
		"http://www.addictingwordgames.com/games/truhangman-2-test",
		"http://www.addictingwordgames.com/games/truwordhunt",
		"http://www.addictingwordgames.com/games/type-and-pop-balloons-skill-game",
		"http://www.addictingwordgames.com/games/type-fast",
		"http://www.addictingwordgames.com/games/type-race",
		"http://www.addictingwordgames.com/games/typeroids",
		"http://www.addictingwordgames.com/games/typhoo",
		"http://www.addictingwordgames.com/games/typing-defense",
		"http://www.addictingwordgames.com/games/typing-game",
		"http://www.addictingwordgames.com/games/typing-go-home",
		"http://www.addictingwordgames.com/games/typing-monster",
		"http://www.addictingwordgames.com/games/typing-speed-test",
		"http://www.addictingwordgames.com/games/typing-with-birds",
		"http://www.addictingwordgames.com/games/ufo-typing",
		"http://www.addictingwordgames.com/games/ultimate-unscramble-1-html-color-code-words",
		"http://www.addictingwordgames.com/games/ultimate-word-search",
		"http://www.addictingwordgames.com/games/ultimate-word-search-mobile",
		"http://www.addictingwordgames.com/games/united-states-word-search",
		"http://www.addictingwordgames.com/games/utterly-cute-dress-up",
		"http://www.addictingwordgames.com/games/valentines-day-word-scramble",
		"http://www.addictingwordgames.com/games/valentines-typing",
		"http://www.addictingwordgames.com/games/valentines-word-search",
		"http://www.addictingwordgames.com/games/vegetables-scramble",
		"http://www.addictingwordgames.com/games/video-hangman",
		"http://www.addictingwordgames.com/games/volleyball-typing",
		"http://www.addictingwordgames.com/games/vowels-in-your-bowels",
		"http://www.addictingwordgames.com/games/waffle-by-flashgamesfancom",
		"http://www.addictingwordgames.com/games/war-of-the-words",
		"http://www.addictingwordgames.com/games/waywords",
		"http://www.addictingwordgames.com/games/wedding-words",
		"http://www.addictingwordgames.com/games/whats-that-spell",
		"http://www.addictingwordgames.com/games/whirled-connections",
		"http://www.addictingwordgames.com/games/whirled-guess",
		"http://www.addictingwordgames.com/games/whizz-words-2",
		"http://www.addictingwordgames.com/games/whizz-wordz",
		"http://www.addictingwordgames.com/games/wild-beauty-makeover",
		"http://www.addictingwordgames.com/games/winter-typing",
		"http://www.addictingwordgames.com/games/wip-1---love-in-heart",
		"http://www.addictingwordgames.com/games/wizard-word-search",
		"http://www.addictingwordgames.com/games/word-blix",
		"http://www.addictingwordgames.com/games/word-blocks",
		"http://www.addictingwordgames.com/games/word-boss",
		"http://www.addictingwordgames.com/games/word-bricks",
		"http://www.addictingwordgames.com/games/word-builder",
		"http://www.addictingwordgames.com/games/word-builder",
		"http://www.addictingwordgames.com/games/word-builder",
		"http://www.addictingwordgames.com/games/word-builder-pro",
		"http://www.addictingwordgames.com/games/word-burst",
		"http://www.addictingwordgames.com/games/word-buster",
		"http://www.addictingwordgames.com/games/word-buster-2",
		"http://www.addictingwordgames.com/games/word-cage",
		"http://www.addictingwordgames.com/games/word-cannon",
		"http://www.addictingwordgames.com/games/word-chain-plus",
		"http://www.addictingwordgames.com/games/word-chaos",
		"http://www.addictingwordgames.com/games/word-collector",
		"http://www.addictingwordgames.com/games/word-cup-3d-game",
		"http://www.addictingwordgames.com/games/word-cup-quiz-2010",
		"http://www.addictingwordgames.com/games/word-detective-demo-1",
		"http://www.addictingwordgames.com/games/word-dimensions",
		"http://www.addictingwordgames.com/games/word-drop",
		"http://www.addictingwordgames.com/games/word-drop",
		"http://www.addictingwordgames.com/games/word-drop",
		"http://www.addictingwordgames.com/games/word-drop-2",
		"http://www.addictingwordgames.com/games/word-find",
		"http://www.addictingwordgames.com/games/word-finder",
		"http://www.addictingwordgames.com/games/word-forge",
		"http://www.addictingwordgames.com/games/word-forge-2",
		"http://www.addictingwordgames.com/games/word-grid",
		"http://www.addictingwordgames.com/games/word-grid",
		"http://www.addictingwordgames.com/games/word-grid",
		"http://www.addictingwordgames.com/games/word-herd",
		"http://www.addictingwordgames.com/games/word-hunter",
		"http://www.addictingwordgames.com/games/word-invaders",
		"http://www.addictingwordgames.com/games/word-invasion",
		"http://www.addictingwordgames.com/games/word-kingdom",
		"http://www.addictingwordgames.com/games/word-machine",
		"http://www.addictingwordgames.com/games/word-magnate",
		"http://www.addictingwordgames.com/games/word-mahjong",
		"http://www.addictingwordgames.com/games/word-maker",
		"http://www.addictingwordgames.com/games/word-mayhem",
		"http://www.addictingwordgames.com/games/word-minute",
		"http://www.addictingwordgames.com/games/word-mountain",
		"http://www.addictingwordgames.com/games/word-out",
		"http://www.addictingwordgames.com/games/word-out",
		"http://www.addictingwordgames.com/games/word-panic",
		"http://www.addictingwordgames.com/games/word-planet",
		"http://www.addictingwordgames.com/games/word-pyramid",
		"http://www.addictingwordgames.com/games/word-rabble",
		"http://www.addictingwordgames.com/games/word-rain",
		"http://www.addictingwordgames.com/games/word-reactor",
		"http://www.addictingwordgames.com/games/word-reaper-concept",
		"http://www.addictingwordgames.com/games/word-roll",
		"http://www.addictingwordgames.com/games/word-ruffle",
		"http://www.addictingwordgames.com/games/word-rush",
		"http://www.addictingwordgames.com/games/word-scramble",
		"http://www.addictingwordgames.com/games/word-scramble",
		"http://www.addictingwordgames.com/games/word-scramble",
		"http://www.addictingwordgames.com/games/word-scramble-ii",
		"http://www.addictingwordgames.com/games/word-search",
		"http://www.addictingwordgames.com/games/word-search",
		"http://www.addictingwordgames.com/games/word-search",
		"http://www.addictingwordgames.com/games/word-search",
		"http://www.addictingwordgames.com/games/word-search",
		"http://www.addictingwordgames.com/games/word-search-2-mobile",
		"http://www.addictingwordgames.com/games/word-search-3",
		"http://www.addictingwordgames.com/games/word-search-4",
		"http://www.addictingwordgames.com/games/word-search-5",
		"http://www.addictingwordgames.com/games/word-search-50",
		"http://www.addictingwordgames.com/games/word-search-maker",
		"http://www.addictingwordgames.com/games/word-shoot",
		"http://www.addictingwordgames.com/games/word-shuffler",
		"http://www.addictingwordgames.com/games/word-slider",
		"http://www.addictingwordgames.com/games/word-smash",
		"http://www.addictingwordgames.com/games/word-snake",
		"http://www.addictingwordgames.com/games/word-spasm",
		"http://www.addictingwordgames.com/games/word-wall",
		"http://www.addictingwordgames.com/games/word-war-i",
		"http://www.addictingwordgames.com/games/word-wheel",
		"http://www.addictingwordgames.com/games/word-wise-jetsetter",
		"http://www.addictingwordgames.com/games/word-work",
		"http://www.addictingwordgames.com/games/word-wrap",
		"http://www.addictingwordgames.com/games/word-wrustler",
		"http://www.addictingwordgames.com/games/word-zapper",
		"http://www.addictingwordgames.com/games/wordblob",
		"http://www.addictingwordgames.com/games/wordboom",
		"http://www.addictingwordgames.com/games/wordchomp",
		"http://www.addictingwordgames.com/games/wordclash",
		"http://www.addictingwordgames.com/games/wordcraft",
		"http://www.addictingwordgames.com/games/wordcross-10",
		"http://www.addictingwordgames.com/games/wordcross-11",
		"http://www.addictingwordgames.com/games/wordcross-12",
		"http://www.addictingwordgames.com/games/wordcross-13",
		"http://www.addictingwordgames.com/games/wordcross-14-twilight",
		"http://www.addictingwordgames.com/games/wordcross-15-wizards",
		"http://www.addictingwordgames.com/games/wordcross-16-christmas",
		"http://www.addictingwordgames.com/games/wordcross-2",
		"http://www.addictingwordgames.com/games/wordcross-3",
		"http://www.addictingwordgames.com/games/wordcross-4",
		"http://www.addictingwordgames.com/games/wordcross-5",
		"http://www.addictingwordgames.com/games/wordcross-6",
		"http://www.addictingwordgames.com/games/wordcross-7",
		"http://www.addictingwordgames.com/games/wordcross-8",
		"http://www.addictingwordgames.com/games/wordcross-9",
		"http://www.addictingwordgames.com/games/wordcross-9in1",
		"http://www.addictingwordgames.com/games/worderfall",
		"http://www.addictingwordgames.com/games/wordex",
		"http://www.addictingwordgames.com/games/wordfight",
		"http://www.addictingwordgames.com/games/wordget",
		"http://www.addictingwordgames.com/games/wordimage",
		"http://www.addictingwordgames.com/games/wordity",
		"http://www.addictingwordgames.com/games/wordknot",
		"http://www.addictingwordgames.com/games/wordkool",
		"http://www.addictingwordgames.com/games/wordomat",
		"http://www.addictingwordgames.com/games/wordquake",
		"http://www.addictingwordgames.com/games/wordrop",
		"http://www.addictingwordgames.com/games/words",
		"http://www.addictingwordgames.com/games/words-game",
		"http://www.addictingwordgames.com/games/words-on-the-beach",
		"http://www.addictingwordgames.com/games/words-worth",
		"http://www.addictingwordgames.com/games/words-worth-2",
		"http://www.addictingwordgames.com/games/wordsearch-%26-crossword",
		"http://www.addictingwordgames.com/games/wordsearch-card-games",
		"http://www.addictingwordgames.com/games/wordsearch-chemical-elements",
		"http://www.addictingwordgames.com/games/wordsearch-constellations",
		"http://www.addictingwordgames.com/games/wordsearch-countries",
		"http://www.addictingwordgames.com/games/wordsearch-easter",
		"http://www.addictingwordgames.com/games/wordsearch-european-countries",
		"http://www.addictingwordgames.com/games/wordsearch-halloween",
		"http://www.addictingwordgames.com/games/wordsearch-internet",
		"http://www.addictingwordgames.com/games/wordsearch-olympic-host-cities",
		"http://www.addictingwordgames.com/games/wordsearch-us-states",
		"http://www.addictingwordgames.com/games/wordslider",
		"http://www.addictingwordgames.com/games/wordsmith",
		"http://www.addictingwordgames.com/games/wordspin",
		"http://www.addictingwordgames.com/games/wordstacks",
		"http://www.addictingwordgames.com/games/wordstone",
		"http://www.addictingwordgames.com/games/wordventures",
		"http://www.addictingwordgames.com/games/wordwar",
		"http://www.addictingwordgames.com/games/wordworks",
		"http://www.addictingwordgames.com/games/wordz",
		"http://www.addictingwordgames.com/games/wordz-mania",
		"http://www.addictingwordgames.com/games/wordzee",
		"http://www.addictingwordgames.com/games/wortsalat",
		"http://www.addictingwordgames.com/games/wrangle",
		"http://www.addictingwordgames.com/games/wrangle-2",
		"http://www.addictingwordgames.com/games/wubble",
		"http://www.addictingwordgames.com/games/wubbles",
		"http://www.addictingwordgames.com/games/xmas-find",
	]
	tags = [
		"word games",
		"bejewelled",
		"sudoku",
		"chess",
		"puzzles",
		"word puzzles",
		"games",
		"fun",
		"free games",
		"word puzzles",
		"puzzle games",
		"addicting games",
		"addicting word games",
		"word search",
		"word finder",
		"online games",
		"free games",
		"language games",
		"learn english",
		"english games",
		"online puzzles",
		"wordament",
		"scrabble",
		"video games",
		"casual games",
		"xbox games",
		"ps4 games",
		"games games",
		"miniclip",
		"spil games",
		"fruit ninja",
		"brain training games",
		"puzzle games",
		"fun word games",
		"fun puzzle games",
		"fun free puzzles",
		"fun free games",
		"fun free word games",
		"funny games",
	]
	def getTags(self):
		'''
		returns a random combination of tags
		'''
		numInSample = random.randint(4, len(self.tags) - 2)
		sample = random.sample(self.tags, numInSample)
		return string.join(sample, ", ")
	def main(self):
		browser = Browser()

		username = sys.argv[1]
		password = sys.argv[2]

		browser.visit('https://www.stumbleupon.com/login')
		browser.fill('user', username)
		browser.fill('pass', password)
		browser.find_by_id('login').click()
		# if browser.is_text_present("Sign in to StumbleUpon"):
		# 	browser.fill('user', username)
		# 	browser.fill('pass', password)
		# 	browser.find_by_id('login').click()
		# import time
		time.sleep(1)

		for url in self.urls:

			browser.visit('https://www.stumbleupon.com/submit')
			browser.fill('url', url)
			browser.find_by_id('safe').click()
			# browser.select("tags", "Online Games")
			browser.find_by_xpath('//select[@name="tags"]/option[@name="Online Games"]').first.click()
			browser.fill('user-tags', self.getTags())
			browser.find_by_css('button[type="submit"]').first.click()

		# if browser.is_text_present('splinter.cobrateam.info'):
		#     print "Yes, the official website was found!"
		# else:
		#     print "No, it wasn't found... We need to improve our SEO techniques"
		time.sleep(7)
		browser.quit()

# print UploadSU().getTags()
UploadSU().main()
