from splinter import Browser
import sys
import random
import string
import time

class UploadSU(object):
	urls = [
	    # "http://www.addictingwordgames.com",
	    "http://www.addictingwordgames.com/game/1-word-10-tries",
		"http://www.addictingwordgames.com/game/10-letter-words",
		"http://www.addictingwordgames.com/game/2-3-4-letter-words",
		"http://www.addictingwordgames.com/game/2009-paris-fashion-show",
		"http://www.addictingwordgames.com/game/4-letter-word-bnc",
		"http://www.addictingwordgames.com/game/60-second-word-search",
		"http://www.addictingwordgames.com/game/60-second-word-search---hungarian-edition",
		"http://www.addictingwordgames.com/game/airport-word-search",
		"http://www.addictingwordgames.com/game/alpha-catcher",
		"http://www.addictingwordgames.com/game/alpha-soup",
		"http://www.addictingwordgames.com/game/alphabenz",
		"http://www.addictingwordgames.com/game/alphabetic-hail",
		"http://www.addictingwordgames.com/game/alphabetics-orbs",
		"http://www.addictingwordgames.com/game/alphabits-scramble",
		"http://www.addictingwordgames.com/game/alphabots",
		"http://www.addictingwordgames.com/game/ambigram",
		"http://www.addictingwordgames.com/game/ambiguity-plus",
		"http://www.addictingwordgames.com/game/anagram-escape",
		"http://www.addictingwordgames.com/game/anagrams",
		"http://www.addictingwordgames.com/game/angry-pig-typing",
		"http://www.addictingwordgames.com/game/animal-kingdom",
		"http://www.addictingwordgames.com/game/animal-word-scramble",
		"http://www.addictingwordgames.com/game/animals",
		"http://www.addictingwordgames.com/game/arthropoda-search",
		"http://www.addictingwordgames.com/game/asteroid-defense",
		"http://www.addictingwordgames.com/game/astronaut-word-search",
		"http://www.addictingwordgames.com/game/b-hangman",
		"http://www.addictingwordgames.com/game/b-speed-typer",
		"http://www.addictingwordgames.com/game/b-speed-typer-ii",
		"http://www.addictingwordgames.com/game/b-speed-typer-iii",
		"http://www.addictingwordgames.com/game/b-word-challenge",
		"http://www.addictingwordgames.com/game/babble",
		"http://www.addictingwordgames.com/game/backpack-travels",
		"http://www.addictingwordgames.com/game/ball-prep-makeover",
		"http://www.addictingwordgames.com/game/banana-breakers",
		"http://www.addictingwordgames.com/game/baseball-word-search",
		"http://www.addictingwordgames.com/game/basketball-word-search",
		"http://www.addictingwordgames.com/game/battle-scribes",
		"http://www.addictingwordgames.com/game/bescrambled",
		"http://www.addictingwordgames.com/game/best-typing",
		"http://www.addictingwordgames.com/game/blackboard-typing",
		"http://www.addictingwordgames.com/game/blocktion",
		"http://www.addictingwordgames.com/game/bloody-hangman",
		"http://www.addictingwordgames.com/game/bodywords-scramble",
		"http://www.addictingwordgames.com/game/bolly-word",
		"http://www.addictingwordgames.com/game/bomb-typing",
		"http://www.addictingwordgames.com/game/bomber-jack",
		"http://www.addictingwordgames.com/game/bookstories",
		"http://www.addictingwordgames.com/game/bouncing-letters",
		"http://www.addictingwordgames.com/game/bouncing-letters",
		"http://www.addictingwordgames.com/game/bowling-word-search",
		"http://www.addictingwordgames.com/game/brick-word",
		"http://www.addictingwordgames.com/game/british-cities",
		"http://www.addictingwordgames.com/game/bubble-typing",
		"http://www.addictingwordgames.com/game/bubble-wordsearch",
		"http://www.addictingwordgames.com/game/bubbletters",
		"http://www.addictingwordgames.com/game/bubblingo",
		"http://www.addictingwordgames.com/game/bumper-stumpers",
		"http://www.addictingwordgames.com/game/bus-typing",
		"http://www.addictingwordgames.com/game/candy-word-search",
		"http://www.addictingwordgames.com/game/canufit",
		"http://www.addictingwordgames.com/game/capital-tower-defense",
		"http://www.addictingwordgames.com/game/cartoon-words",
		"http://www.addictingwordgames.com/game/casebreaker",
		"http://www.addictingwordgames.com/game/celebrities-word-game",
		"http://www.addictingwordgames.com/game/chain-master",
		"http://www.addictingwordgames.com/game/chainz",
		"http://www.addictingwordgames.com/game/childrens-logic",
		"http://www.addictingwordgames.com/game/chirstmas-word-search",
		"http://www.addictingwordgames.com/game/christmas-treats",
		"http://www.addictingwordgames.com/game/christmas-word-finders",
		"http://www.addictingwordgames.com/game/christmas-word-search",
		"http://www.addictingwordgames.com/game/christmas-word-search",
		"http://www.addictingwordgames.com/game/cinderella-wordsearch",
		"http://www.addictingwordgames.com/game/circus-word-search",
		"http://www.addictingwordgames.com/game/city-of-words",
		"http://www.addictingwordgames.com/game/clockwords-act-i",
		"http://www.addictingwordgames.com/game/clockwords-prelude",
		"http://www.addictingwordgames.com/game/clothing-scramble",
		"http://www.addictingwordgames.com/game/clueless-crossword",
		"http://www.addictingwordgames.com/game/cocktail-sparkles-beauty-makeover",
		"http://www.addictingwordgames.com/game/code-quest",
		"http://www.addictingwordgames.com/game/coin-typing",
		"http://www.addictingwordgames.com/game/colour-balls",
		"http://www.addictingwordgames.com/game/colour-trap",
		"http://www.addictingwordgames.com/game/comet-busters",
		"http://www.addictingwordgames.com/game/compound-letters",
		"http://www.addictingwordgames.com/game/countries",
		"http://www.addictingwordgames.com/game/cowboy-word-search",
		"http://www.addictingwordgames.com/game/cross-7",
		"http://www.addictingwordgames.com/game/crossword-ninja-cat",
		"http://www.addictingwordgames.com/game/crossword-puzzle",
		"http://www.addictingwordgames.com/game/crossword-scramble",
		"http://www.addictingwordgames.com/game/cube-crash-wordz",
		"http://www.addictingwordgames.com/game/cupid-typing",
		"http://www.addictingwordgames.com/game/cupid-typing-2",
		"http://www.addictingwordgames.com/game/custom-word-search",
		"http://www.addictingwordgames.com/game/custom-word-search-vol-2",
		"http://www.addictingwordgames.com/game/cypher-five",
		"http://www.addictingwordgames.com/game/dates-scrmable-words",
		"http://www.addictingwordgames.com/game/december-21",
		"http://www.addictingwordgames.com/game/delicious-lasagna",
		"http://www.addictingwordgames.com/game/demi-tuhan-wars",
		"http://www.addictingwordgames.com/game/deword",
		"http://www.addictingwordgames.com/game/dewordeca",
		"http://www.addictingwordgames.com/game/dinosaur-word-search",
		"http://www.addictingwordgames.com/game/ditloid",
		"http://www.addictingwordgames.com/game/dooma",
		"http://www.addictingwordgames.com/game/dragon-word-search",
		"http://www.addictingwordgames.com/game/drop-a-block",
		"http://www.addictingwordgames.com/game/easter-bunnies-typing",
		"http://www.addictingwordgames.com/game/easy-words-scramble-1",
		"http://www.addictingwordgames.com/game/easy-words-scramble-2",
		"http://www.addictingwordgames.com/game/ego-hangman",
		"http://www.addictingwordgames.com/game/electro",
		"http://www.addictingwordgames.com/game/empathy",
		"http://www.addictingwordgames.com/game/extreme-crossword-2",
		"http://www.addictingwordgames.com/game/fabulous-makeover-diva-style",
		"http://www.addictingwordgames.com/game/face-eater-typing",
		"http://www.addictingwordgames.com/game/fairy-magic",
		"http://www.addictingwordgames.com/game/family-guy-solitaire",
		"http://www.addictingwordgames.com/game/farm-animals-word-search",
		"http://www.addictingwordgames.com/game/farm-word-search",
		"http://www.addictingwordgames.com/game/fast-food-word-search",
		"http://www.addictingwordgames.com/game/fast-typing",
		"http://www.addictingwordgames.com/game/find-that-animal",
		"http://www.addictingwordgames.com/game/find-words",
		"http://www.addictingwordgames.com/game/finda-word",
		"http://www.addictingwordgames.com/game/fish-and-words",
		"http://www.addictingwordgames.com/game/fishaword",
		"http://www.addictingwordgames.com/game/flabberblast",
		"http://www.addictingwordgames.com/game/fleep",
		"http://www.addictingwordgames.com/game/flower-word-search",
		"http://www.addictingwordgames.com/game/food-for-thought",
		"http://www.addictingwordgames.com/game/foods-scramble",
		"http://www.addictingwordgames.com/game/football-word-search",
		"http://www.addictingwordgames.com/game/found-ghastly-language",
		"http://www.addictingwordgames.com/game/free-words-by-flashgamesfancom",
		"http://www.addictingwordgames.com/game/fruit-swordman-typing",
		"http://www.addictingwordgames.com/game/fruit-swordman-typing-2",
		"http://www.addictingwordgames.com/game/fruits-typing",
		"http://www.addictingwordgames.com/game/fruits-word-scramble",
		"http://www.addictingwordgames.com/game/fuseword",
		"http://www.addictingwordgames.com/game/galactic-word-war",
		"http://www.addictingwordgames.com/game/galax",
		"http://www.addictingwordgames.com/game/galgenmaennchen",
		"http://www.addictingwordgames.com/game/gems-typing",
		"http://www.addictingwordgames.com/game/ghost",
		"http://www.addictingwordgames.com/game/gone-fishing-word-search",
		"http://www.addictingwordgames.com/game/grammar-bee",
		"http://www.addictingwordgames.com/game/gravitoons",
		"http://www.addictingwordgames.com/game/greek-legends-nous",
		"http://www.addictingwordgames.com/game/guess-it",
		"http://www.addictingwordgames.com/game/guess-the-words",
		"http://www.addictingwordgames.com/game/guess-what",
		"http://www.addictingwordgames.com/game/gunman-typing",
		"http://www.addictingwordgames.com/game/halloween-hangman",
		"http://www.addictingwordgames.com/game/halloween-treats",
		"http://www.addictingwordgames.com/game/halloween-word-dig",
		"http://www.addictingwordgames.com/game/halloween-word-scramble",
		"http://www.addictingwordgames.com/game/halloween-word-search",
		"http://www.addictingwordgames.com/game/halloween-word-search",
		"http://www.addictingwordgames.com/game/hang-a-bot-state-capitals",
		"http://www.addictingwordgames.com/game/hang-em-high",
		"http://www.addictingwordgames.com/game/hangman",
		"http://www.addictingwordgames.com/game/hangman",
		"http://www.addictingwordgames.com/game/hangman",
		"http://www.addictingwordgames.com/game/hangman",
		"http://www.addictingwordgames.com/game/hangman",
		"http://www.addictingwordgames.com/game/hangman",
		"http://www.addictingwordgames.com/game/hangman-3-languages",
		"http://www.addictingwordgames.com/game/hangman-classic",
		"http://www.addictingwordgames.com/game/hangman-pirate",
		"http://www.addictingwordgames.com/game/hangman-puzzle-game",
		"http://www.addictingwordgames.com/game/hangmas",
		"http://www.addictingwordgames.com/game/hangword",
		"http://www.addictingwordgames.com/game/hardest-typing",
		"http://www.addictingwordgames.com/game/hero-word-search",
		"http://www.addictingwordgames.com/game/hex-words",
		"http://www.addictingwordgames.com/game/hex-words",
		"http://www.addictingwordgames.com/game/hidden-words",
		"http://www.addictingwordgames.com/game/horse-racing-typing",
		"http://www.addictingwordgames.com/game/horse-racing-typing-2",
		"http://www.addictingwordgames.com/game/hospital-word-scramble",
		"http://www.addictingwordgames.com/game/hot-balloon-typing",
		"http://www.addictingwordgames.com/game/humpty",
		"http://www.addictingwordgames.com/game/insect-word-search",
		"http://www.addictingwordgames.com/game/isogram-puzzle",
		"http://www.addictingwordgames.com/game/itsy-bitsy-spider",
		"http://www.addictingwordgames.com/game/jigsaw-open-top",
		"http://www.addictingwordgames.com/game/jigsaw-sunlit-buddah",
		"http://www.addictingwordgames.com/game/jigsaw-zebra-stripes",
		"http://www.addictingwordgames.com/game/jobs-word-scrambles",
		"http://www.addictingwordgames.com/game/jumble-jong",
		"http://www.addictingwordgames.com/game/jumble-laya",
		"http://www.addictingwordgames.com/game/kanji-memory-game-pro-edition",
		"http://www.addictingwordgames.com/game/kekata",
		"http://www.addictingwordgames.com/game/kids-first-play",
		"http://www.addictingwordgames.com/game/knights",
		"http://www.addictingwordgames.com/game/kot-word-search",
		"http://www.addictingwordgames.com/game/lateral---the-word-association-game",
		"http://www.addictingwordgames.com/game/learning-spanish",
		"http://www.addictingwordgames.com/game/letter-blocks",
		"http://www.addictingwordgames.com/game/letter-blocks",
		"http://www.addictingwordgames.com/game/letter-matrix",
		"http://www.addictingwordgames.com/game/letter-rip",
		"http://www.addictingwordgames.com/game/letter-scramble",
		"http://www.addictingwordgames.com/game/letter-twist",
		"http://www.addictingwordgames.com/game/letter-weave",
		"http://www.addictingwordgames.com/game/letters-3d",
		"http://www.addictingwordgames.com/game/letters-catch",
		"http://www.addictingwordgames.com/game/lightning-typing-2",
		"http://www.addictingwordgames.com/game/lightning-typing-3",
		"http://www.addictingwordgames.com/game/lilei-and-hanmeimei-typing",
		"http://www.addictingwordgames.com/game/linguistics",
		"http://www.addictingwordgames.com/game/linked",
		"http://www.addictingwordgames.com/game/lion-typing",
		"http://www.addictingwordgames.com/game/little-red-riding-hood-wordsearch",
		"http://www.addictingwordgames.com/game/logoleptic",
		"http://www.addictingwordgames.com/game/logophobia",
		"http://www.addictingwordgames.com/game/lotus-hall-room-escape-game",
		"http://www.addictingwordgames.com/game/love-word-scrambler",
		"http://www.addictingwordgames.com/game/lunchbreak",
		"http://www.addictingwordgames.com/game/magic-forest-puzzle",
		"http://www.addictingwordgames.com/game/magic-words",
		"http://www.addictingwordgames.com/game/makeup-word-search",
		"http://www.addictingwordgames.com/game/mancala",
		"http://www.addictingwordgames.com/game/mantra",
		"http://www.addictingwordgames.com/game/meaning-fall",
		"http://www.addictingwordgames.com/game/mick-letterton",
		"http://www.addictingwordgames.com/game/million-dollar-words---halloween-edition",
		"http://www.addictingwordgames.com/game/million-dollar-words---november-archive",
		"http://www.addictingwordgames.com/game/mind-flipper",
		"http://www.addictingwordgames.com/game/missed-letter",
		"http://www.addictingwordgames.com/game/mixed-words",
		"http://www.addictingwordgames.com/game/monkeyboard",
		"http://www.addictingwordgames.com/game/monster-word-search",
		"http://www.addictingwordgames.com/game/multiplayer-8ball-pool",
		"http://www.addictingwordgames.com/game/muscle-word-worm-shuffle",
		"http://www.addictingwordgames.com/game/music-word-search",
		"http://www.addictingwordgames.com/game/must-pop-words",
		"http://www.addictingwordgames.com/game/mustache-slap",
		"http://www.addictingwordgames.com/game/my-word",
		"http://www.addictingwordgames.com/game/mystery-words",
		"http://www.addictingwordgames.com/game/mystic-river",
		"http://www.addictingwordgames.com/game/mystic-words",
		"http://www.addictingwordgames.com/game/new-romantic-scramble",
		"http://www.addictingwordgames.com/game/newspuzzles",
		"http://www.addictingwordgames.com/game/nfl-typing-2",
		"http://www.addictingwordgames.com/game/ninja-cat-and-zombie-dinosaurs",
		"http://www.addictingwordgames.com/game/ninja-word-search",
		"http://www.addictingwordgames.com/game/north-korea--launch-typing",
		"http://www.addictingwordgames.com/game/number-riddle",
		"http://www.addictingwordgames.com/game/ocean-word-search",
		"http://www.addictingwordgames.com/game/onomastica",
		"http://www.addictingwordgames.com/game/palindromes",
		"http://www.addictingwordgames.com/game/pantechnicon-connection",
		"http://www.addictingwordgames.com/game/parking-wordsearch",
		"http://www.addictingwordgames.com/game/party-glamour-makeover",
		"http://www.addictingwordgames.com/game/patchword",
		"http://www.addictingwordgames.com/game/patchwork-lite-pt-br",
		"http://www.addictingwordgames.com/game/patchwork-lite-us-en",
		"http://www.addictingwordgames.com/game/phrase-crazy",
		"http://www.addictingwordgames.com/game/piano-typing",
		"http://www.addictingwordgames.com/game/pick-up-strings",
		"http://www.addictingwordgames.com/game/picture-vocabulary-test",
		"http://www.addictingwordgames.com/game/pirate-word-search",
		"http://www.addictingwordgames.com/game/plant-madness",
		"http://www.addictingwordgames.com/game/pollinator-puzzle",
		"http://www.addictingwordgames.com/game/pop-star-word-search",
		"http://www.addictingwordgames.com/game/pretty-chic-girl-makeover",
		"http://www.addictingwordgames.com/game/princess-word-search",
		"http://www.addictingwordgames.com/game/puppet-theatre---mystical-example",
		"http://www.addictingwordgames.com/game/puzzwords",
		"http://www.addictingwordgames.com/game/quarkstar-typing",
		"http://www.addictingwordgames.com/game/quickpick",
		"http://www.addictingwordgames.com/game/qwerty-space",
		"http://www.addictingwordgames.com/game/ramble-scramble---come2play",
		"http://www.addictingwordgames.com/game/random-word-scramble",
		"http://www.addictingwordgames.com/game/random-word-unscramble",
		"http://www.addictingwordgames.com/game/rapperzapper",
		"http://www.addictingwordgames.com/game/rebus-2",
		"http://www.addictingwordgames.com/game/recite-chinese-word",
		"http://www.addictingwordgames.com/game/red-carpet-star-search",
		"http://www.addictingwordgames.com/game/redbeards-treasure",
		"http://www.addictingwordgames.com/game/reggie-red-fur",
		"http://www.addictingwordgames.com/game/reincarnations-awakening",
		"http://www.addictingwordgames.com/game/reincarnations-awakening-chapter-1",
		"http://www.addictingwordgames.com/game/relationship-words",
		"http://www.addictingwordgames.com/game/rhymetime",
		"http://www.addictingwordgames.com/game/riff-raff",
		"http://www.addictingwordgames.com/game/rise-and-fall",
		"http://www.addictingwordgames.com/game/roboflu",
		"http://www.addictingwordgames.com/game/rock-band-word-search",
		"http://www.addictingwordgames.com/game/rocket-typing",
		"http://www.addictingwordgames.com/game/rocket-typing-2",
		"http://www.addictingwordgames.com/game/rocket-writer",
		"http://www.addictingwordgames.com/game/rowowor",
		"http://www.addictingwordgames.com/game/safari-word-search",
		"http://www.addictingwordgames.com/game/save-me",
		"http://www.addictingwordgames.com/game/save-pandus",
		"http://www.addictingwordgames.com/game/save-the-girl",
		"http://www.addictingwordgames.com/game/save-the-monkey",
		"http://www.addictingwordgames.com/game/school-word-search",
		"http://www.addictingwordgames.com/game/scramble-words-creatures",
		"http://www.addictingwordgames.com/game/scribble",
		"http://www.addictingwordgames.com/game/scrimble",
		"http://www.addictingwordgames.com/game/scroll-block",
		"http://www.addictingwordgames.com/game/sea-star-scramble",
		"http://www.addictingwordgames.com/game/sea-typing",
		"http://www.addictingwordgames.com/game/search-the-sand",
		"http://www.addictingwordgames.com/game/semantic-wars",
		"http://www.addictingwordgames.com/game/sensational-wedding-makeover",
		"http://www.addictingwordgames.com/game/shark-antennas-co",
		"http://www.addictingwordgames.com/game/shooting-manish",
		"http://www.addictingwordgames.com/game/shooting-typing",
		"http://www.addictingwordgames.com/game/shootwords",
		"http://www.addictingwordgames.com/game/shrimp-bruschetta",
		"http://www.addictingwordgames.com/game/skater-word-search",
		"http://www.addictingwordgames.com/game/skedaddle",
		"http://www.addictingwordgames.com/game/sky-banner",
		"http://www.addictingwordgames.com/game/skyline",
		"http://www.addictingwordgames.com/game/sleeping-beauty-wordsearch",
		"http://www.addictingwordgames.com/game/slidoword",
		"http://www.addictingwordgames.com/game/slippery-words---little-red-riding-hood",
		"http://www.addictingwordgames.com/game/smily-word-builder-games",
		"http://www.addictingwordgames.com/game/snail-invasion",
		"http://www.addictingwordgames.com/game/snail-invasion-extended",
		"http://www.addictingwordgames.com/game/snakes-n-letters",
		"http://www.addictingwordgames.com/game/snappy-1up",
		"http://www.addictingwordgames.com/game/snappy-2up",
		"http://www.addictingwordgames.com/game/snow-typer",
		"http://www.addictingwordgames.com/game/snow-typing",
		"http://www.addictingwordgames.com/game/snow-words",
		"http://www.addictingwordgames.com/game/snowboard-word-search",
		"http://www.addictingwordgames.com/game/soccer-word-search",
		"http://www.addictingwordgames.com/game/solar-system-word-search",
		"http://www.addictingwordgames.com/game/solo-words",
		"http://www.addictingwordgames.com/game/soul-pawnshop-escape",
		"http://www.addictingwordgames.com/game/space-invader",
		"http://www.addictingwordgames.com/game/space-words-recharged",
		"http://www.addictingwordgames.com/game/space-words-scramble",
		"http://www.addictingwordgames.com/game/spacetrace",
		"http://www.addictingwordgames.com/game/speed-spell",
		"http://www.addictingwordgames.com/game/speedwords",
		"http://www.addictingwordgames.com/game/spell-fest",
		"http://www.addictingwordgames.com/game/spell-words",
		"http://www.addictingwordgames.com/game/spelling-drill",
		"http://www.addictingwordgames.com/game/spelling-kitty",
		"http://www.addictingwordgames.com/game/spicy-snail-foods",
		"http://www.addictingwordgames.com/game/spooky-find",
		"http://www.addictingwordgames.com/game/sports-word-search",
		"http://www.addictingwordgames.com/game/sports-wordsearch",
		"http://www.addictingwordgames.com/game/starmageddon",
		"http://www.addictingwordgames.com/game/stick-ryu-typing",
		"http://www.addictingwordgames.com/game/summer-typing",
		"http://www.addictingwordgames.com/game/supermodel-word-search",
		"http://www.addictingwordgames.com/game/swap",
		"http://www.addictingwordgames.com/game/swappign",
		"http://www.addictingwordgames.com/game/swizzled",
		"http://www.addictingwordgames.com/game/swizzlepop",
		"http://www.addictingwordgames.com/game/swizzlepop---whirled",
		"http://www.addictingwordgames.com/game/synonymous",
		"http://www.addictingwordgames.com/game/szvadsz",
		"http://www.addictingwordgames.com/game/target-words",
		"http://www.addictingwordgames.com/game/taxicab-word-search",
		"http://www.addictingwordgames.com/game/teach-bolly",
		"http://www.addictingwordgames.com/game/terminacore",
		"http://www.addictingwordgames.com/game/tetword-pro",
		"http://www.addictingwordgames.com/game/textmate",
		"http://www.addictingwordgames.com/game/thanksgiving-word-scamble",
		"http://www.addictingwordgames.com/game/thanksgiving-word-search",
		"http://www.addictingwordgames.com/game/that-word-game",
		"http://www.addictingwordgames.com/game/the-amazing-puzzle-factory",
		"http://www.addictingwordgames.com/game/the-apiculturists-laboratory",
		"http://www.addictingwordgames.com/game/the-apothecarys-cellar",
		"http://www.addictingwordgames.com/game/the-britney-apocalypse",
		"http://www.addictingwordgames.com/game/the-crossword-game-v10",
		"http://www.addictingwordgames.com/game/the-fly-typing",
		"http://www.addictingwordgames.com/game/the-gardener",
		"http://www.addictingwordgames.com/game/the-hanged-man",
		"http://www.addictingwordgames.com/game/the-hanged-man-2",
		"http://www.addictingwordgames.com/game/the-random-test-i",
		"http://www.addictingwordgames.com/game/the-stairway",
		"http://www.addictingwordgames.com/game/the-stairway-mobile",
		"http://www.addictingwordgames.com/game/the-time-trap",
		"http://www.addictingwordgames.com/game/the-tortoise-and-the-hare---wordsearch",
		"http://www.addictingwordgames.com/game/the-typing-of-the-ghosts",
		"http://www.addictingwordgames.com/game/the-wizards-notebook",
		"http://www.addictingwordgames.com/game/the-word-factory",
		"http://www.addictingwordgames.com/game/the-word-pyramid",
		"http://www.addictingwordgames.com/game/the-wordies",
		"http://www.addictingwordgames.com/game/toootem",
		"http://www.addictingwordgames.com/game/top-cards",
		"http://www.addictingwordgames.com/game/tropical-mix-game",
		"http://www.addictingwordgames.com/game/truhangman",
		"http://www.addictingwordgames.com/game/truhangman-2-test",
		"http://www.addictingwordgames.com/game/truwordhunt",
		"http://www.addictingwordgames.com/game/type-and-pop-balloons-skill-game",
		"http://www.addictingwordgames.com/game/type-fast",
		"http://www.addictingwordgames.com/game/type-race",
		"http://www.addictingwordgames.com/game/typeroids",
		"http://www.addictingwordgames.com/game/typhoo",
		"http://www.addictingwordgames.com/game/typing-defense",
		"http://www.addictingwordgames.com/game/typing-game",
		"http://www.addictingwordgames.com/game/typing-go-home",
		"http://www.addictingwordgames.com/game/typing-monster",
		"http://www.addictingwordgames.com/game/typing-speed-test",
		"http://www.addictingwordgames.com/game/typing-with-birds",
		"http://www.addictingwordgames.com/game/ufo-typing",
		"http://www.addictingwordgames.com/game/ultimate-unscramble-1-html-color-code-words",
		"http://www.addictingwordgames.com/game/ultimate-word-search",
		"http://www.addictingwordgames.com/game/ultimate-word-search-mobile",
		"http://www.addictingwordgames.com/game/united-states-word-search",
		"http://www.addictingwordgames.com/game/utterly-cute-dress-up",
		"http://www.addictingwordgames.com/game/valentines-day-word-scramble",
		"http://www.addictingwordgames.com/game/valentines-typing",
		"http://www.addictingwordgames.com/game/valentines-word-search",
		"http://www.addictingwordgames.com/game/vegetables-scramble",
		"http://www.addictingwordgames.com/game/video-hangman",
		"http://www.addictingwordgames.com/game/volleyball-typing",
		"http://www.addictingwordgames.com/game/vowels-in-your-bowels",
		"http://www.addictingwordgames.com/game/waffle-by-flashgamesfancom",
		"http://www.addictingwordgames.com/game/war-of-the-words",
		"http://www.addictingwordgames.com/game/waywords",
		"http://www.addictingwordgames.com/game/wedding-words",
		"http://www.addictingwordgames.com/game/whats-that-spell",
		"http://www.addictingwordgames.com/game/whirled-connections",
		"http://www.addictingwordgames.com/game/whirled-guess",
		"http://www.addictingwordgames.com/game/whizz-words-2",
		"http://www.addictingwordgames.com/game/whizz-wordz",
		"http://www.addictingwordgames.com/game/wild-beauty-makeover",
		"http://www.addictingwordgames.com/game/winter-typing",
		"http://www.addictingwordgames.com/game/wip-1---love-in-heart",
		"http://www.addictingwordgames.com/game/wizard-word-search",
		"http://www.addictingwordgames.com/game/word-blix",
		"http://www.addictingwordgames.com/game/word-blocks",
		"http://www.addictingwordgames.com/game/word-boss",
		"http://www.addictingwordgames.com/game/word-bricks",
		"http://www.addictingwordgames.com/game/word-builder",
		"http://www.addictingwordgames.com/game/word-builder",
		"http://www.addictingwordgames.com/game/word-builder",
		"http://www.addictingwordgames.com/game/word-builder-pro",
		"http://www.addictingwordgames.com/game/word-burst",
		"http://www.addictingwordgames.com/game/word-buster",
		"http://www.addictingwordgames.com/game/word-buster-2",
		"http://www.addictingwordgames.com/game/word-cage",
		"http://www.addictingwordgames.com/game/word-cannon",
		"http://www.addictingwordgames.com/game/word-chain-plus",
		"http://www.addictingwordgames.com/game/word-chaos",
		"http://www.addictingwordgames.com/game/word-collector",
		"http://www.addictingwordgames.com/game/word-cup-3d-game",
		"http://www.addictingwordgames.com/game/word-cup-quiz-2010",
		"http://www.addictingwordgames.com/game/word-detective-demo-1",
		"http://www.addictingwordgames.com/game/word-dimensions",
		"http://www.addictingwordgames.com/game/word-drop",
		"http://www.addictingwordgames.com/game/word-drop",
		"http://www.addictingwordgames.com/game/word-drop",
		"http://www.addictingwordgames.com/game/word-drop-2",
		"http://www.addictingwordgames.com/game/word-find",
		"http://www.addictingwordgames.com/game/word-finder",
		"http://www.addictingwordgames.com/game/word-forge",
		"http://www.addictingwordgames.com/game/word-forge-2",
		"http://www.addictingwordgames.com/game/word-grid",
		"http://www.addictingwordgames.com/game/word-grid",
		"http://www.addictingwordgames.com/game/word-grid",
		"http://www.addictingwordgames.com/game/word-herd",
		"http://www.addictingwordgames.com/game/word-hunter",
		"http://www.addictingwordgames.com/game/word-invaders",
		"http://www.addictingwordgames.com/game/word-invasion",
		"http://www.addictingwordgames.com/game/word-kingdom",
		"http://www.addictingwordgames.com/game/word-machine",
		"http://www.addictingwordgames.com/game/word-magnate",
		"http://www.addictingwordgames.com/game/word-mahjong",
		"http://www.addictingwordgames.com/game/word-maker",
		"http://www.addictingwordgames.com/game/word-mayhem",
		"http://www.addictingwordgames.com/game/word-minute",
		"http://www.addictingwordgames.com/game/word-mountain",
		"http://www.addictingwordgames.com/game/word-out",
		"http://www.addictingwordgames.com/game/word-out",
		"http://www.addictingwordgames.com/game/word-panic",
		"http://www.addictingwordgames.com/game/word-planet",
		"http://www.addictingwordgames.com/game/word-pyramid",
		"http://www.addictingwordgames.com/game/word-rabble",
		"http://www.addictingwordgames.com/game/word-rain",
		"http://www.addictingwordgames.com/game/word-reactor",
		"http://www.addictingwordgames.com/game/word-reaper-concept",
		"http://www.addictingwordgames.com/game/word-roll",
		"http://www.addictingwordgames.com/game/word-ruffle",
		"http://www.addictingwordgames.com/game/word-rush",
		"http://www.addictingwordgames.com/game/word-scramble",
		"http://www.addictingwordgames.com/game/word-scramble",
		"http://www.addictingwordgames.com/game/word-scramble",
		"http://www.addictingwordgames.com/game/word-scramble-ii",
		"http://www.addictingwordgames.com/game/word-search",
		"http://www.addictingwordgames.com/game/word-search",
		"http://www.addictingwordgames.com/game/word-search",
		"http://www.addictingwordgames.com/game/word-search",
		"http://www.addictingwordgames.com/game/word-search",
		"http://www.addictingwordgames.com/game/word-search-2-mobile",
		"http://www.addictingwordgames.com/game/word-search-3",
		"http://www.addictingwordgames.com/game/word-search-4",
		"http://www.addictingwordgames.com/game/word-search-5",
		"http://www.addictingwordgames.com/game/word-search-50",
		"http://www.addictingwordgames.com/game/word-search-maker",
		"http://www.addictingwordgames.com/game/word-shoot",
		"http://www.addictingwordgames.com/game/word-shuffler",
		"http://www.addictingwordgames.com/game/word-slider",
		"http://www.addictingwordgames.com/game/word-smash",
		"http://www.addictingwordgames.com/game/word-snake",
		"http://www.addictingwordgames.com/game/word-spasm",
		"http://www.addictingwordgames.com/game/word-wall",
		"http://www.addictingwordgames.com/game/word-war-i",
		"http://www.addictingwordgames.com/game/word-wheel",
		"http://www.addictingwordgames.com/game/word-wise-jetsetter",
		"http://www.addictingwordgames.com/game/word-work",
		"http://www.addictingwordgames.com/game/word-wrap",
		"http://www.addictingwordgames.com/game/word-wrustler",
		"http://www.addictingwordgames.com/game/word-zapper",
		"http://www.addictingwordgames.com/game/wordblob",
		"http://www.addictingwordgames.com/game/wordboom",
		"http://www.addictingwordgames.com/game/wordchomp",
		"http://www.addictingwordgames.com/game/wordclash",
		"http://www.addictingwordgames.com/game/wordcraft",
		"http://www.addictingwordgames.com/game/wordcross-10",
		"http://www.addictingwordgames.com/game/wordcross-11",
		"http://www.addictingwordgames.com/game/wordcross-12",
		"http://www.addictingwordgames.com/game/wordcross-13",
		"http://www.addictingwordgames.com/game/wordcross-14-twilight",
		"http://www.addictingwordgames.com/game/wordcross-15-wizards",
		"http://www.addictingwordgames.com/game/wordcross-16-christmas",
		"http://www.addictingwordgames.com/game/wordcross-2",
		"http://www.addictingwordgames.com/game/wordcross-3",
		"http://www.addictingwordgames.com/game/wordcross-4",
		"http://www.addictingwordgames.com/game/wordcross-5",
		"http://www.addictingwordgames.com/game/wordcross-6",
		"http://www.addictingwordgames.com/game/wordcross-7",
		"http://www.addictingwordgames.com/game/wordcross-8",
		"http://www.addictingwordgames.com/game/wordcross-9",
		"http://www.addictingwordgames.com/game/wordcross-9in1",
		"http://www.addictingwordgames.com/game/worderfall",
		"http://www.addictingwordgames.com/game/wordex",
		"http://www.addictingwordgames.com/game/wordfight",
		"http://www.addictingwordgames.com/game/wordget",
		"http://www.addictingwordgames.com/game/wordimage",
		"http://www.addictingwordgames.com/game/wordity",
		"http://www.addictingwordgames.com/game/wordknot",
		"http://www.addictingwordgames.com/game/wordkool",
		"http://www.addictingwordgames.com/game/wordomat",
		"http://www.addictingwordgames.com/game/wordquake",
		"http://www.addictingwordgames.com/game/wordrop",
		"http://www.addictingwordgames.com/game/words",
		"http://www.addictingwordgames.com/game/words-game",
		"http://www.addictingwordgames.com/game/words-on-the-beach",
		"http://www.addictingwordgames.com/game/words-worth",
		"http://www.addictingwordgames.com/game/words-worth-2",
		"http://www.addictingwordgames.com/game/wordsearch-%26-crossword",
		"http://www.addictingwordgames.com/game/wordsearch-card-games",
		"http://www.addictingwordgames.com/game/wordsearch-chemical-elements",
		"http://www.addictingwordgames.com/game/wordsearch-constellations",
		"http://www.addictingwordgames.com/game/wordsearch-countries",
		"http://www.addictingwordgames.com/game/wordsearch-easter",
		"http://www.addictingwordgames.com/game/wordsearch-european-countries",
		"http://www.addictingwordgames.com/game/wordsearch-halloween",
		"http://www.addictingwordgames.com/game/wordsearch-internet",
		"http://www.addictingwordgames.com/game/wordsearch-olympic-host-cities",
		"http://www.addictingwordgames.com/game/wordsearch-us-states",
		"http://www.addictingwordgames.com/game/wordslider",
		"http://www.addictingwordgames.com/game/wordsmith",
		"http://www.addictingwordgames.com/game/wordspin",
		"http://www.addictingwordgames.com/game/wordstacks",
		"http://www.addictingwordgames.com/game/wordstone",
		"http://www.addictingwordgames.com/game/wordventures",
		"http://www.addictingwordgames.com/game/wordwar",
		"http://www.addictingwordgames.com/game/wordworks",
		"http://www.addictingwordgames.com/game/wordz",
		"http://www.addictingwordgames.com/game/wordz-mania",
		"http://www.addictingwordgames.com/game/wordzee",
		"http://www.addictingwordgames.com/game/wortsalat",
		"http://www.addictingwordgames.com/game/wrangle",
		"http://www.addictingwordgames.com/game/wrangle-2",
		"http://www.addictingwordgames.com/game/wubble",
		"http://www.addictingwordgames.com/game/wubbles",
		"http://www.addictingwordgames.com/game/xmas-find",
	]
	tags = [
		"word games",
		"bejewelled",
		"sudoku",
		"chess",
		"puzzles",
		"word puzzles",
		"games",
		"fun",
		"free games",
		"word puzzles",
		"puzzle games",
		"addicting games",
		"addicting word games",
		"word search",
		"word finder",
		"online games",
		"free games",
		"language games",
		"learn english",
		"english games",
		"online puzzles",
		"wordament",
		"scrabble",
		"video games",
		"casual games",
		"xbox games",
		"ps4 games",
		"games games",
		"miniclip",
		"spil games",
		"fruit ninja",
		"brain training games",
		"puzzle games",
		"fun word games",
		"fun puzzle games",
		"fun free puzzles",
		"fun free games",
		"fun free word games",
		"funny games",
	]
	def getTags(self):
		'''
		returns a random combination of tags
		'''
		numInSample = random.randint(4, len(self.tags) - 2)
		sample = random.sample(self.tags, numInSample)
		return string.join(sample, ", ")
	def main(self):
		browser = Browser()

		username = sys.argv[1]
		password = sys.argv[2]

		browser.visit('https://www.stumbleupon.com/login')
		browser.fill('user', username)
		browser.fill('pass', password)
		browser.find_by_id('login').click()
		# if browser.is_text_present("Sign in to StumbleUpon"):
		# 	browser.fill('user', username)
		# 	browser.fill('pass', password)
		# 	browser.find_by_id('login').click()
		# import time
		time.sleep(1)

		for url in self.urls:

			browser.visit('https://www.stumbleupon.com/submit')
			browser.fill('url', url)
			browser.find_by_id('safe').click()
			# browser.select("tags", "Online Games")
			browser.find_by_xpath('//select[@name="tags"]/option[@name="Online Games"]').first.click()
			browser.fill('user-tags', self.getTags())
			browser.find_by_css('button[type="submit"]').first.click()
			time.sleep(1)

		# if browser.is_text_present('splinter.cobrateam.info'):
		#     print "Yes, the official website was found!"
		# else:
		#     print "No, it wasn't found... We need to improve our SEO techniques"
		time.sleep(7)
		browser.quit()

# print UploadSU().getTags()
UploadSU().main()
